#!/bin/bash
sed -i 's/Color(0xFFFEE2E2)/MaterialTheme.colorScheme.errorContainer/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFF991B1B)/MaterialTheme.colorScheme.onErrorContainer/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFFFEF3C7)/MaterialTheme.colorScheme.tertiaryContainer/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFF92400E)/MaterialTheme.colorScheme.onTertiaryContainer/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFFD1FAE5)/MaterialTheme.colorScheme.primaryContainer/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFF065F46)/MaterialTheme.colorScheme.onPrimaryContainer/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFFFFEBEE)/MaterialTheme.colorScheme.errorContainer/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xE8E8F5E9)/MaterialTheme.colorScheme.primaryContainer/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFFE8F5E9)/MaterialTheme.colorScheme.primaryContainer/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFF2E7D32)/MaterialTheme.colorScheme.primary/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFF1B5E20)/MaterialTheme.colorScheme.onPrimaryContainer/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFFF7C5CC)/MaterialTheme.colorScheme.errorContainer/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFFC8E6C9)/MaterialTheme.colorScheme.primaryContainer/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFF81C784)/MaterialTheme.colorScheme.primary/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFF4CAF50)/MaterialTheme.colorScheme.primary/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFFE57373)/MaterialTheme.colorScheme.error/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFFFFF3E0)/MaterialTheme.colorScheme.tertiaryContainer/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFFE65100)/MaterialTheme.colorScheme.onTertiaryContainer/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFFC62828)/MaterialTheme.colorScheme.error/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFFFFFDE7)/MaterialTheme.colorScheme.secondaryContainer/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFFFFF176)/MaterialTheme.colorScheme.onSecondaryContainer/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFF5D4037)/MaterialTheme.colorScheme.onSecondaryContainer/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFFFBC02D)/MaterialTheme.colorScheme.tertiary/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFF9B1C1C)/MaterialTheme.colorScheme.error/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFFC81E1E)/MaterialTheme.colorScheme.error/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFFFEF9C3)/MaterialTheme.colorScheme.tertiaryContainer/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFF854D0E)/MaterialTheme.colorScheme.onTertiaryContainer/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFFFDE8E8)/MaterialTheme.colorScheme.errorContainer/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFF1C1B1F)/MaterialTheme.colorScheme.onSurface/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFFF5F5F0)/MaterialTheme.colorScheme.surfaceVariant/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFFFFE5EC)/MaterialTheme.colorScheme.errorContainer/g' app/src/main/java/com/example/ui/PosApp.kt
sed -i 's/Color(0xFF3EB489)/MaterialTheme.colorScheme.primary/g' app/src/main/java/com/example/ui/PosApp.kt
