package com.example.ui

import androidx.compose.runtime.mutableStateOf

object Translator {
    val currentLanguageState = mutableStateOf("Tiếng Việt")

    private val englishMap = mapOf(
        "Tồn kho từ nhiều đến ít" to "Stock: High to Low",
        "Tổng tồn từ thấp đến cao" to "Total stock: Low to High",
        "Tổng tồn từ cao đến thấp" to "Total stock: High to Low",
        "Chọn phương thức thanh toán" to "Select payment method",
        "Tiền mặt" to "Cash",
        "Chuyển khoản" to "Transfer",
        "Tên sản phẩm" to "Product Name",
        "SL" to "Qty",
        "Đơn giá" to "Price",
        "Thành tiền" to "Total",
        "Tồn còn lại: " to "Remaining stock: ",
        "Khác" to "Other",
        "Vốn: " to "Cost: ",
        "sản phẩm" to "products",
        "Tổng lãi: " to "Total Profit: ",
        "Tổng lãi" to "Total Profit",
        "Giờ: " to "Time: ",
        "Ngày" to "Date",
        "Tháng" to "Month",
        "Lãi: " to "Profit: ",
        "Mã hóa đơn: " to "Invoice ID: ",
        "Số lượng: " to "Quantity: ",
        "Nhập: " to "Import: ",
        "Bán: " to "Sell: ",
        "Tồn: " to "Stock: ",
        "Tồn kho: " to "Inventory: ",
        "Giá nhập: " to "Import Price: ",
        "Đơn hàng nợ: " to "Debt Orders: ",
        "Hẹn trả gần nhất: " to "Nearest Due Date: ",
        "Tổng số hóa đơn nợ: " to "Total Debt Invoices: ",
        "Tổng tiền nợ: " to "Total Debt: ",
        "Còn nợ: " to "Remaining Debt: ",
        "Đã trả: " to "Paid: ",
        "Thời gian mua: " to "Purchase Time: ",
        "Hẹn trả: " to "Due Date: ",
        "đơn hàng" to "orders",
        "1 đơn hàng" to "1 order",
        "Tiền lãi: " to "Profit: ",
        "Bố cục hiển thị: " to "Display Layout: ",
        "Dạng lưới G-View" to "Grid (G-View)",
        "Dạng danh sách L-View" to "List (L-View)",
        "Tiếng Anh" to "English",
        "Tiếng Trung Quốc" to "Chinese",
        "Liên hệ (Zalo): " to "Contact (Zalo): ",
        "sp" to "unit",
        "Chưa hẹn" to "Not scheduled",

        " mặt hàng" to " items",
        " mặt hàng liên quan" to " related items",
        " mặt hàng thuộc danh mục này)" to " items in this category)",
        " đơn hàng" to " orders",
        "' không?" to "'?",
        "' không?\n(Có " to "'?\n(There are ",
        "' khỏi giỏ hàng?" to "' from the cart?",
        "(Bấm để sửa)" to "(Tap to edit)",
        "(Ấn vào mặt hàng để chỉnh sửa)" to "(Tap on item to edit)",
        "- Chuyển khoản chi trả: %s (Khả dụng: %s)" to "- Bank transfer paid: %s (Available: %s)",
        "- Tiền mặt chi trả: %s (Khả dụng: %s)" to "- Cash paid: %s (Available: %s)",
        "Bán công nợ" to "Sell on credit",
        "Bán hàng" to "Sales",
        "Bán lẻ" to "Retail",
        "Bán nợ" to "Sell on credit",
        "Báo cáo doanh thu" to "Sales Report",
        "Bạn có chắc chắn muốn hoàn tiền cho hóa đơn này không?" to "Are you sure you want to refund this invoice?",
        "Bạn có chắc chắn muốn hoàn tiền cho hóa đơn này không?\nHành động này sẽ xóa hóa đơn và hoàn lại toàn bộ sản phẩm vào kho hàng." to "Are you sure you want to refund this invoice?\nThis will delete the invoice and return all products to inventory.",
        "Bạn có chắc chắn muốn tắt bán công nợ cho hóa đơn này không?" to "Are you sure you want to disable selling on credit for this invoice?",
        "Bạn có chắc chắn muốn xóa TẤT CẢ các mặt hàng và danh mục không? Hành động này không thể hoàn tác." to "Are you sure you want to delete ALL products and categories? This cannot be undone.",
        "Bạn có chắc chắn muốn xóa TẤT CẢ dữ liệu (mặt hàng, danh mục, hóa đơn...) không? Hành động này không thể hoàn tác." to "Are you sure you want to delete ALL data (products, categories, invoices...)? This cannot be undone.",
        "Bạn có chắc chắn muốn xóa danh mục '" to "Are you sure you want to delete category '",
        "Bạn có chắc chắn muốn xóa danh mục này? Hành động này sẽ xóa vĩnh viễn khỏi thiết bị!" to "Are you sure you want to delete this category? This action is permanent!",
        "Bạn có chắc chắn muốn xóa mặt hàng '" to "Are you sure you want to delete '",
        "Bạn có chắc chắn muốn xóa sản phẩm '\${productToRemoveFromCategory?.name}' khỏi danh mục này không?" to "Are you sure you want to remove the product '\${productToRemoveFromCategory?.name}' from this category?",
        "Bạn có chắc chắn muốn xóa sản phẩm '%s' khỏi hóa đơn này?" to "Are you sure you want to delete product '%s' from this invoice?",
        "Bạn có chắc chắn muốn xóa sản phẩm này? Hành động này sẽ xóa vĩnh viễn khỏi thiết bị!" to "Are you sure you want to delete this product? This action is permanent!",
        "Bạn có chắc chắn muốn xóa toàn bộ công nợ của khách hàng %s? Toàn bộ các hóa đơn nợ của khách hàng này sẽ được xóa." to "Are you sure you want to clear all debts of customer %s? All credit invoices of this customer will be deleted.",
        "Bạn có chắc chắn muốn xóa tất cả sản phẩm, hóa đơn và danh mục khỏi thiết bị không? Hành động này không thể hoàn tác!" to "Are you sure you want to delete all products, invoices, and categories? This action cannot be undone!",
        "Bạn có chắc chắn muốn xóa đơn nhập hàng này? Hành động này sẽ hoàn tác và khôi phục (giảm) số lượng tồn kho tương ứng của các sản phẩm trong đơn." to "Are you sure you want to delete this purchase order? This action will undo and restore (reduce) the corresponding inventory stock of products in the order.",
        "Bản sao lưu " to "Backup ",
        "Bảng quản lý" to "Management Board",
        "Bật chi phí phát sinh" to "Enable additional costs",
        "Bố cục" to "Layout",
        "Chi Tiết Công Nợ" to "Debt Details",
        "Chi phí phát sinh" to "Additional Costs",
        "Chi tiết Hóa đơn" to "Invoice Details",
        "Chi tiết đơn hàng:" to "Order details:",
        "Cho phép gởi thông báo hóa đơn và tải hình ảnh sản phẩm" to "Allow invoice notifications & product image loading",
        "Cho phép gửi thông báo hóa đơn, truy cập lịch và tải hình ảnh sản phẩm" to "Allow invoice notifications, calendar access, and product image uploads",
        "Chuyển khoản" to "Bank Transfer",
        "Chưa có bản sao lưu tự động nào (bản đầu tiên sẽ được tạo vào lúc 23:50)." to "No auto-backups yet (the first will be created at 23:50).",
        "Chưa có danh mục nào được thiết lập" to "No categories set up yet",
        "Chưa có danh mục nào. Nhấp '+' để thêm." to "No categories yet. Click '+' to add.",
        "Chưa có hóa đơn nào được tạo" to "No receipts created yet",
        "Chưa có khách hàng nào được lưu lịch sử mua hàng." to "No customer purchase histories found.",
        "Chưa có mặt hàng nào trong đơn" to "No items in the order yet",
        "Chưa có mặt hàng nào. Nhấn nút + bên dưới để tạo mới." to "No products yet. Click + below to create one.",
        "Chưa có sản phẩm nào. Nhấp '+' để thêm." to "No products yet. Click '+' to add.",
        "Chưa có đơn nhập hàng nào" to "No purchase orders yet",
        "Chưa phân nhóm" to "Unassigned",
        "Chế độ tối (Dark mode)" to "Dark Mode",
        "Chỉnh sửa mặt hàng" to "Edit Product",
        "Chỉnh sửa sản phẩm" to "Edit product",
        "Chỉnh sửa tên danh mục" to "Edit category name",
        "Chỉnh sửa đơn nhập" to "Edit purchase order",
        "Đồng bộ nhà cung cấp" to "Sync suppliers",
        "Đồng bộ hóa nhà cung cấp từ các đơn nhập hàng cũ" to "Sync supplier names from past import orders",
        "Đồng bộ thành công" to "Synced successfully",
        "Chọn danh mục" to "Select Category",
        "Chọn hoặc nhập danh mục mới..." to "Select or enter new category...",
        "Chọn hoặc nhập nhà cung cấp..." to "Select or enter supplier...",
        "Chọn hình ảnh" to "Choose image",
        "Chọn hình ảnh từ Gallery" to "Select image from Gallery",
        "Chọn màu sắc hiển thị" to "Select Category Accent Colour",
        "Chọn sản phẩm có sẵn" to "Select existing product",
        "Chức năng trực tuyến đang được triển khai" to "Online feature is under development",
        "Cài đặt" to "Settings",
        "Cài đặt hệ thống" to "System Settings",
        "Có " to "There are ",
        "Cảnh báo" to "Warning",
        "Cảnh báo đặc biệt nguy hiểm!" to "Danger Zone!",
        "Cấp quyền cho tất cả" to "Grant All Permissions",
        "Cấp quyền hệ thống" to "System Permissions",
        "Cấu hình" to "Configure",
        "Cấu hình POS" to "POS Configuration",
        "CẬP NHẬT" to "UPDATE",
        "Cập nhật" to "Update",
        "Cập nhật nhanh tồn kho" to "Quick Stock Update",
        "Cập nhật thông tin" to "Update Info",
        "Cập nhật trực tiếp giá nhập hệ thống:" to "Directly update system cost price:",
        "Cập nhật đơn nhập hàng thành công!" to "Purchase order updated successfully!",
        "Danh mục" to "Categories",
        "Danh mục (mặc định 'Không danh mục')" to "Category (default 'Uncategorized')",
        "Danh sách hàng nhập" to "List of purchased goods",
        "Danh sách hóa đơn bán hàng" to "Sales Invoice List",
        "Danh sách mặt hàng:" to "Item List:",
        "Danh sách đơn hàng nợ:" to "List of credit orders:",
        "Danh sách đơn hàng đã lấy:" to "Purchased order list:",
        "Doanh thu theo sản phẩm" to "Sales Revenue by Product",
        "Doanh thu và lợi nhuận bán hàng" to "Revenue & Profit",
        "Dọn dẹp dữ liệu" to "Clean Up Data",
        "Giao dịch đã được ghi nhận vào lịch sử." to "The transaction has been recorded.",
        "Giá bán" to "Selling price",
        "Giá bán sỉ & lẻ thực tế sẽ được hiển thị công khai trên giao diện POS." to "The actual wholesale & retail prices will be displayed publicly on the POS.",
        "Giá bán: " to "Price: ",
        "Giá nhập" to "Import Price",
        "Giá nhập mới" to "New cost price",
        "Giá: " to "Price: ",
        "Giỏ hàng" to "Cart",
        "Giỏ hàng của bạn đang trống" to "Your cart is empty",
        "Giỏ hàng hiện có %d mặt hàng" to "Cart has %d items",
        "Giỏ hàng hiện tại đang trống. Vui lòng thêm sản phẩm vào giỏ hàng trước!" to "The cart is empty. Please add products first!",
        "Giỏ hàng đang trống" to "Cart is empty",
        "Giới thiệu" to "About",
        "Gán các sản phẩm đã có vào danh mục này:" to "Assign existing products to this category:",
        "Gợi ý sản phẩm:" to "Suggested products:",
        "Gợi ý từ đơn hàng trước của nhà cung cấp này:" to "Suggestions from this supplier's previous orders:",
        "HOÀN THÀNH ĐƠN" to "COMPLETE ORDER",
        "HOÀN TIỀN & HỦY HÓA ĐƠN" to "REFUND & CANCEL INVOICE",
        "HOÀN TẤT" to "DONE",
        "Hoàn tiền" to "Refund",
        "Hoàn tiền thành công!" to "Refund Successful!",
        "Hàng tồn kho" to "Inventory",
        "Hóa đơn" to "Invoices",
        "Hóa đơn chi tiết" to "Detailed Invoice",
        "Hóa đơn đã được lưu trữ trong danh mục lịch sử. Hàng tồn kho đã được tự động khấu trừ." to "Invoice archived in history. Inventory has been automatically deducted.",
        "HỦY" to "CANCEL",
        "Hủy" to "Cancel",
        "Hủy bỏ" to "Cancel",
        "Kho hàng:" to "Warehouse:",
        "Khách hàng & Đối tác" to "Customers & Partners",
        "Khách hàng:" to "Customer:",
        "Khách hàng: " to "Customer: ",
        "Khách lẻ" to "Walk-in customer",
        "Khôi phục" to "Restore",
        "Không" to "No",
        "Không có khách hàng nào đang nợ." to "No customers currently have outstanding debt.",
        "Không có sản phẩm nào trong danh mục này" to "No products in this category",
        "Không có sản phẩm nào tồn kho." to "No products in inventory.",
        "Không danh mục" to "Uncategorized",
        "Không thể lưu lịch hẹn vì thiếu quyền truy cập lịch." to "Cannot save schedule due to missing calendar permissions.",
        "Không thể mở trình chọn tệp: " to "Cannot open file picker: ",
        "Không thể mở trình ghi tệp: " to "Cannot open file writer: ",
        "Không thể tạo sự kiện lịch" to "Cannot create calendar event",
        "Không tìm thấy khách hàng phù hợp." to "No matching customers found.",
        "Không tìm thấy mặt hàng nào để gán." to "No products found to assign.",
        "Không tìm thấy mặt hàng để chỉnh sửa" to "Product to edit not found",
        "Không tìm thấy sản phẩm nào" to "No products found",
        "Không tìm thấy sản phẩm phù hợp." to "No matching products found.",
        "Kết quả tìm kiếm:" to "Search results:",
        "Liên hệ (Zalo): 0964935879" to "Contact (Zalo): 0964935879",
        "LƯU" to "SAVE",
        "Lưu" to "Save",
        "Lưu danh mục" to "Save Category",
        "Lưu lịch hẹn" to "Save Schedule",
        "Lưu sản phẩm" to "Save Product",
        "Lưu thất bại: " to "Save failed: ",
        "Lập đơn nhập hàng" to "Create Purchase Order",
        "Lập đơn nhập hàng thành công!" to "Purchase order created successfully!",
        "Lịch hẹn thanh toán" to "Payment Schedule",
        "Lịch sử hóa đơn" to "Receipt History",
        "Lịch sử mua hàng và tìm kiếm khách hàng" to "Purchase history and customer search",
        "Lịch sử mua sắm" to "Purchase History",
        "Lỗ: " to "Loss: ",
        "Lỗi lấy ID sự kiện lịch" to "Error retrieving calendar event ID",
        "LỢI NHUẬN (TIỀN LÃI):" to "PROFIT (EARNINGS):",
        "Lợi nhuận: " to "Profit: ",
        "Mã HD: #" to "Inv Code: #",
        "Mô tả sản phẩm..." to "Product description...",
        "Mô tả..." to "Description...",
        "Mặt Hàng" to "Products",
        "Mở rộng" to "Expand",
        "Mục Tra Soát Hóa Đơn" to "Invoice Reconciliation",
        "Nguồn tiền" to "Funds Source",
        "Ngôn ngữ (Language)" to "Language",
        "Người sáng lập: Cường lâm" to "Founder: Cuong Lam",
        "Nhà cung cấp" to "Supplier",
        "Nhà cung cấp ẩn danh" to "Anonymous Supplier",
        "Nhấp để khôi phục nhanh dữ liệu từ bản này" to "Click to quickly restore from this backup",
        "Nhập Tên Khách Hàng (Tự động lưu)" to "Enter Customer Name (Auto-saved)",
        "Nhập giá bán" to "Enter sell price",
        "Nhập giá bán..." to "Enter sell price...",
        "Nhập giá nhập" to "Enter import price",
        "Nhập giá nhập..." to "Enter import price...",
        "Nhập gần đây: " to "Recently imported: ",
        "Nhập mô tả danh mục..." to "Enter category description...",
        "Nhập mô tả..." to "Enter description...",
        "Nhập sao lưu" to "Import backup",
        "Nhập số lượng mới" to "Enter new quantity",
        "Nhập số lượng tồn kho ban đầu..." to "Enter initial stock...",
        "Nhập số tiền thanh toán" to "Enter payment amount",
        "Nhập tên danh mục" to "Enter category name",
        "Nhập tên khách hàng..." to "Enter customer name...",
        "Nhập tên mặt hàng..." to "Enter product name...",
        "Nhập tên mới cho khách hàng %s:" to "Enter new name for customer %s:",
        "Nhập tên nhà cung cấp..." to "Enter supplier name...",
        "Nhập tên sản phẩm" to "Enter product name",
        "Phiên bản 1.3.9" to "Version 1.3.9",
        "Phiên bản: 1.3.9" to "Version: 1.3.9",
        "Phân Loại Danh Mục" to "Categories",
        "Phân vùng nhóm danh mục hàng hóa để tối ưu hóa việc phân nhóm hiển thị trên POS." to "Organize product categories to optimize POS displays.",
        "Quyền lịch đã được cấp. Hãy nhấn 'Lưu lịch hẹn' một lần nữa để lưu." to "Calendar permission granted. Tap 'Save Schedule' again to save.",
        "Quản lý" to "Management",
        "Quản lý Danh mục" to "Category Management",
        "Quản lý Khách hàng" to "Customer Management",
        "Quản lý Mặt hàng" to "Product Management",
        "Quản lý công nợ" to "Debt Management",
        "Quản lý hàng tồn" to "Inventory Management",
        "Quản lý kho hàng" to "Inventory Management",
        "Quản lý nhập hàng" to "Purchase Management",
        "Quản lý và điều phối các kho hàng của bạn" to "Manage and coordinate your warehouses",
        "Quản lý đơn nhập hàng, thêm nhà cung cấp, cập nhật giá vốn và số lượng tồn kho." to "Manage purchase orders, suppliers, cost prices, and inventory stock.",
        "Sao Lưu Tự Động Hàng Ngày (23:50)" to "Daily Auto Backup (23:50)",
        "Sao lưu" to "Backup",
        "Sao lưu & Khôi phục dữ liệu" to "Backup & Restore Data",
        "Sao lưu cơ sở dữ liệu bán hàng đám mây" to "Cloud Sales Database Backup",
        "Sao lưu dữ liệu" to "Backup Data",
        "Sao lưu thành công" to "Backup successful",
        "Sao lưu toàn bộ dữ liệu có trong ứng dụng không bỏ sót thông tin nào cả (sản phẩm, danh mục, hóa đơn, đơn nhập, cấu hình hệ thống, hình ảnh). Hỗ trợ kích thước tệp tối đa lên tới 800MB." to "Backup all data in the application completely (products, categories, invoices, purchase orders, system config, images). Supports file size up to 800MB.",
        "SĐT: " to "Phone: ",
        "Sản phẩm" to "Products",
        "Sản phẩm sắp hết hàng (< 5)" to "Items running low (< 5)",
        "Sản phẩm đã hết hàng (0)" to "Out of stock (0)",
        "Số lượng" to "Quantity",
        "Số lượng nhập" to "Purchase Quantity",
        "Số lượng phải lớn hơn 0!" to "Quantity must be greater than 0!",
        "Số lượng tồn kho" to "In Stock",
        "Số lượng vượt quá hàng tồn kho! Tự động điều chỉnh về %d" to "Quantity exceeds stock! Automatically adjusted to %d",
        "Số tiền chi phí phát sinh" to "Additional cost amount",
        "Số tiền thanh toán vượt quá hạn mức khả dụng trong nguồn tiền. Bạn có chắc chắn muốn tiếp tục?" to "Payment amount exceeds the available limit in the funds source. Are you sure you want to continue?",
        "Số tiền thanh toán vượt quá tổng nợ hiện tại!" to "Payment amount exceeds the current total debt!",
        "SỬA ĐƠN" to "EDIT ORDER",
        "Sử dụng ảnh mẫu thiết bị có sẵn" to "Use sample image",
        "Sửa" to "Edit",
        "Sửa Sản Phẩm" to "Edit Product",
        "Sửa nguồn tiền" to "Edit Funds Source",
        "Sửa thông tin mặt hàng nhập" to "Edit imported product info",
        "Sửa tên khách hàng" to "Edit customer name",
        "THANH TOÁN Giao Dịch" to "PROCEED TO CHECKOUT",
        "THÊM" to "ADD",
        "Thanh Toán Thành Công!" to "Payment Successful!",
        "Thanh toán CK" to "Bank Transfer Pay",
        "Thanh toán TM" to "Cash Pay",
        "Thanh toán thành công!" to "Checkout Successful!",
        "Thanh toán trước" to "Pay in Advance",
        "Theo dõi hàng trong kho" to "Track stock",
        "Theo dõi lượng tồn kho từng sản phẩm, đơn giá nhập và tổng giá trị tồn kho toàn hệ thống." to "Track inventory quantity, cost prices, and total system stock value.",
        "Theo dõi tồn kho" to "Track Inventory",
        "Theo dõi và quản lý các đơn hàng bán nợ, danh sách khách hàng nợ và lịch hẹn thanh toán." to "Track and manage sales on credit, customer debts, and payment schedules.",
        "Thu gọn" to "Collapse",
        "Thành tiền: " to "Subtotal: ",
        "Thêm danh mục" to "Add Category",
        "Thêm danh mục mới" to "Add New Category",
        "Thêm hàng mới" to "Add New Product",
        "Thêm mặt hàng" to "Add Product",
        "Thêm mặt hàng từ giỏ hàng" to "Add items from cart",
        "Thêm sản phẩm" to "Add Product",
        "Thêm sản phẩm nhập" to "Add purchased product",
        "Thêm từ giỏ hàng" to "Add from cart",
        "Thống kê tồn kho" to "Stock Level Statistics",
        "Thời gian:" to "Time:",
        "Tiết kiệm pin và dịu mắt khi sử dụng ban đêm" to "Save battery & reduce eye strain at night",
        "Tiền mặt" to "Cash",
        "Tiền mặt (VND)" to "Cash (VND)",
        "Tiền mặt: " to "Cash: ",
        "Tra soát hóa đơn" to "Invoice Reconciliation",
        "Trong kho" to "In stock",
        "Trạng thái:" to "Status:",
        "Trở về" to "Back",
        "Tài khoản (VND)" to "Account (VND)",
        "Tài khoản: " to "Account: ",
        "Tên Khách Hàng" to "Customer Name",
        "Tên danh mục" to "Category Name",
        "Tên danh mục..." to "Category name...",
        "Tên khách hàng mới" to "New customer name",
        "Tên khách hàng..." to "Customer name...",
        "Tên mặt hàng" to "Product Name",
        "Tên mặt hàng *" to "Product Name *",
        "Tên nhà cung cấp" to "Supplier Name",
        "Tên sản phẩm..." to "Product name...",
        "Tìm kiếm" to "Search",
        "Tìm kiếm hóa đơn..." to "Search invoices...",
        "Tìm kiếm khách hàng..." to "Search customers...",
        "Tìm kiếm sản phẩm..." to "Search products...",
        "Tìm tên sản phẩm..." to "Search product name...",
        "Tạo Danh Mục" to "Create Category",
        "Tạo Sản Phẩm" to "Create Product",
        "Tạo danh mục" to "Create Category",
        "Tạo mặt hàng" to "Create Product",
        "Tạo mặt hàng mới" to "Create new product",
        "Tải ảnh sản phẩm" to "Upload product image",
        "Tất cả" to "All",
        "Tất cả các quyền cần thiết đã được cấp" to "All required permissions have been granted",
        "Tắt bán nợ" to "Disable selling on credit",
        "Tệp và Sao Lưu JSON" to "JSON Files & Backups",
        "Tối ưu hóa quản lý và tra soát khách hàng" to "Optimize management & customer tracking",
        "Tổng Doanh Thu Hoạt Động" to "Total Sales Revenue",
        "Tổng công nợ" to "Total Debt",
        "Tổng cộng tiền hàng:" to "Total Amount:",
        "Tổng cộng:" to "Total:",
        "Tổng giá trị đơn nhập:" to "Total Purchase Value:",
        "Tổng lỗ: " to "Total Loss: ",
        "Tổng lợi nhuận thực tế" to "Actual Total Profit",
        "Tổng quan sản phẩm" to "Product Overview",
        "Tổng số sản phẩm trong kho" to "Total items in stock",
        "Tổng tiền hàng:" to "Total Amount:",
        "Tổng tiền tồn kho" to "Total Inventory Value",
        "Tổng tồn" to "Total Stock Value",
        "Tự động sao lưu" to "Auto Backup",
        "Tự động tự sao lưu lúc 23:50 hàng ngày. Ghi đè tự động." to "Auto backup daily at 23:50. Auto-overwrite.",
        "Vui lòng cấp quyền đặt báo thức để sao lưu đúng giờ" to "Please grant alarm permission to backup on schedule",
        "Vui lòng nhập số lượng hợp lệ!" to "Please enter a valid quantity!",
        "Vui lòng nhập số tiền hợp lệ" to "Please enter a valid amount",
        "Vui lòng nhập tên danh mục" to "Please enter category name",
        "Vui lòng nhập tên khách hàng" to "Please enter customer name",
        "Vui lòng nhập tên mặt hàng" to "Please enter product name",
        "Vui lòng nhập đầy đủ thông tin!" to "Please enter all required fields!",
        "Vui lòng điền đúng giá trị!" to "Please enter valid numeric values!",
        "Vui lòng ấn nút + ở góc phải bên dưới để lập đơn hàng nhập mới." to "Please press the + button at the bottom right to create a new purchase order.",
        "Ví dụ: 50000" to "Example: 50000",
        "Ví dụ: 500000" to "Example: 500000",
        "Xem lịch sử mua hàng, chi tiết các hóa đơn và sản phẩm mà khách hàng đã lấy." to "View purchase histories, receipt details, and bought products.",
        "Xem, thêm mặt hàng mới, thiết lập giá bán, và cấu hình lượng hàng tồn kho." to "View, add products, set prices, and configure stock.",
        "Xuất hoặc nhập toàn bộ thông tin về sản phẩm, giá cả, tồn kho, ảnh sản phẩm, khách hàng và đơn hàng dưới dạng tệp JSON." to "Export or import all product, price, stock, image, customer and order data as JSON file.",
        "Xuất sao lưu" to "Export backup",
        "XÓA" to "DELETE",
        "XÓA TOÀN BỘ CƠ SỞ DỮ LIỆU" to "DELETE ENTIRE DATABASE",
        "XÓA ĐƠN" to "DELETE ORDER",
        "Xác nhận" to "Confirm",
        "Xác nhận hoàn tiền" to "Confirm Refund",
        "Xác nhận tiếp tục" to "Confirm to continue",
        "Xác nhận tắt bán nợ" to "Confirm disabling credit sales",
        "Xác nhận vượt hạn mức chi trả" to "Confirm exceeding limit",
        "Xác nhận xóa" to "Confirm deletion",
        "Xác nhận xóa danh mục" to "Confirm Delete Category",
        "Xác nhận xóa danh mục?" to "Confirm Delete Category?",
        "Xác nhận xóa nợ" to "Confirm debt clearing",
        "Xác nhận xóa sản phẩm khỏi danh mục" to "Confirm removing product from category",
        "Xác nhận xóa sản phẩm?" to "Confirm Delete Product?",
        "Xác nhận xóa tất cả" to "Confirm Delete All",
        "Xác nhận xóa tất cả dữ liệu" to "Confirm Delete All Data",
        "Xác thực sao lưu" to "Verify Backup",
        "Xóa" to "Delete",
        "Xóa hết" to "Delete All",
        "Xóa khỏi danh mục" to "Remove from category",
        "Xóa mặt hàng" to "Delete Product",
        "Xóa nợ" to "Clear debt",
        "Xóa tìm kiếm" to "Clear search",
        "Xóa tất cả dữ liệu" to "Delete All Data",
        "Xóa tất cả dữ liệu hiện có khỏi hệ thống (sản phẩm, danh mục, hóa đơn...)" to "Delete all existing data from system (products, categories, invoices...)",
        "Xóa tất cả mặt hàng & danh mục" to "Delete All Products & Categories",
        "Xóa tất cả mặt hàng và danh mục hiện có ra khỏi hệ thống" to "Delete all existing products and categories from system",
        "mặt hàng" to "items",
        "Đang sao lưu..." to "Backing up...",
        "Đang thuộc danh mục khác" to "In another category",
        "Điều chỉnh nguồn tiền" to "Adjust funds source",
        "Đã cấp quyền hoàn tất" to "Permissions granted successfully",
        "Đã cập nhật nguồn tiền thành công!" to "Funds source adjusted successfully!",
        "Đã cập nhật sản phẩm!" to "Product updated!",
        "Đã cập nhật thông tin mặt hàng" to "Product updated successfully",
        "Đã cập nhật tồn kho thành công!" to "Inventory updated successfully!",
        "Đã cập quyền hoàn tất" to "Permissions granted successfully",
        "Đã hoàn tiền" to "Refunded",
        "Đã hoàn trả sản phẩm vào kho và xóa hóa đơn!" to "Returned products to stock and deleted invoice!",
        "Đã lưu danh mục mới" to "New category saved",
        "Đã lưu danh mục thành công!" to "Category saved successfully!",
        "Đã lưu lịch hẹn thanh toán vào lịch máy!" to "Payment schedule saved to device calendar!",
        "Đã lưu mặt hàng mới" to "New product saved",
        "Đã lưu sản phẩm thành công!" to "Product saved successfully!",
        "Đã thanh toán" to "Paid",
        "Đã thanh toán trước thành công số tiền: " to "Successfully pre-paid: ",
        "Đã thêm các mặt hàng từ giỏ hàng vào hóa đơn!" to "Added items from cart to the invoice!",
        "Đã trả hàng và hoàn lại tiền." to "Returned items and refunded.",
        "Đã xóa sản phẩm khỏi hóa đơn!" to "Product deleted from invoice!",
        "Đã xóa toàn bộ công nợ thành công!" to "Cleared all debts successfully!",
        "Đã xóa toàn bộ dữ liệu" to "All data deleted successfully",
        "Đã xóa toàn bộ sản phẩm và danh mục" to "Deleted all products and categories",
        "Đã xóa đơn nhập hàng và cập nhật lại tồn kho" to "Deleted purchase order and restored inventory",
        "Đã đến lịch thanh toán của " to "Payment schedule is due for ",
        "Đã đổi thành " to "Changed to ",
        "Đóng" to "Close",
        "Đăng nhập hoặc Đăng ký" to "Log In or Register",
        "Đăng nhập tài khoản" to "Account Login",
        "Đơn" to "Order",
        "Đơn giá:" to "Unit price:",
        "Đại diện trên POS" to "POS Representation",
        "Ảnh sản phẩm" to "Product Image",
        "Để đảm bảo an toàn cho dữ liệu bán hàng của bạn, vui lòng thực hiện sao lưu trước khi tiến hành xóa toàn bộ dữ liệu khỏi hệ thống." to "To ensure the safety of your sales data, please perform a backup before proceeding with deleting all system data.",
        "Lập báo cáo" to "Generate Report",
        "Từ ngày" to "From Date",
        "Đến ngày" to "To Date",
        "Kết quả báo cáo" to "Report Results",
        "Chọn nhà cung cấp" to "Select Supplier",
        "Tổng đơn nhập" to "Total import orders",
        "Tổng tiền nhập" to "Total import amount",
        "lập báo cáo nhập hàng" to "create import report",
        "Tổng đơn hàng" to "Total Orders",
        "Tổng doanh thu" to "Total Revenue",
        "Tổng lỗ" to "Total Loss",
        "Bạn đang có mặt hàng trong đơn nhập. Bạn có muốn lưu nháp đơn hàng này không?" to "You have items in your import order. Do you want to save this order as a draft?",
        "Lưu nháp" to "Save Draft",
        "Thoát" to "Exit",
        "NHÁP" to "DRAFT",
        "HOÀN THÀNH" to "COMPLETE",
        "Đã lưu nháp đơn nhập hàng!" to "Import order saved as draft!",
        "Đã xác nhận hoàn thành đơn nhập hàng!" to "Confirmed completion of import order!",
        "Căn chỉnh ảnh sản phẩm" to "Adjust product image",
        "Di chuyển hoặc phóng to/thu nhỏ ảnh để vừa khung hình 1:1" to "Move or zoom the image to fit the 1:1 square frame",
        "Lỗi lưu ảnh đã cắt" to "Error saving cropped image",
        "Lỗi cắt ảnh" to "Error cropping image",
        "Không thể tải hình ảnh" to "Unable to load image",
        "Thu phóng" to "Zoom",
        "Xoay 90°" to "Rotate 90°",
        "Hoàn hàng" to "Return goods",
        "Hàng tồn:" to "Stock:",
        "Tính toán tiền hoàn lại:" to "Calculate Refund:",
        "Xác nhận hoàn hàng" to "Confirm Return",
        "Bạn có chắc chắn muốn hoàn" to "Are you sure you want to return",
        "sản phẩm với tổng số tiền là" to "items with the total amount of",
        "không?\n\nHệ thống sẽ tự động trừ kho và cộng lại tiền mặt." to "?\n\nThe system will automatically deduct stock and refund cash.",
        "Số lượng hoàn" to "Return Quantity"
    )

    private val chineseMap = mapOf(
        "Tồn kho từ nhiều đến ít" to "库存: 从多到少",
        "Tổng tồn từ thấp đến cao" to "总库存价值: 从低到高",
        "Tổng tồn từ cao đến thấp" to "总库存价值: 从高到低",
        "Chọn phương thức thanh toán" to "选择付款方式",
        "Tiền mặt" to "现金",
        "Chuyển khoản" to "转账",
        "Tên sản phẩm" to "产品名称",
        "SL" to "数量",
        "Đơn giá" to "单价",
        "Thành tiền" to "总价",
        "Tồn còn lại: " to "剩余库存: ",
        "Khác" to "其他",
        "Vốn: " to "成本: ",
        "sản phẩm" to "产品",
        "Tổng lãi: " to "总利润: ",
        "Tổng lãi" to "总利润",
        "Giờ: " to "时间: ",
        "Ngày" to "日期",
        "Tháng" to "月",
        "Lãi: " to "利润: ",
        "Mã hóa đơn: " to "发票号: ",
        "Số lượng: " to "数量: ",
        "Nhập: " to "进价: ",
        "Bán: " to "售价: ",
        "Tồn: " to "库存: ",
        "Tồn kho: " to "库存量: ",
        "Giá nhập: " to "进价: ",
        "Đơn hàng nợ: " to "欠款订单: ",
        "Hẹn trả gần nhất: " to "最近还款日: ",
        "Tổng số hóa đơn nợ: " to "总欠款发票数: ",
        "Tổng tiền nợ: " to "总欠款: ",
        "Còn nợ: " to "剩余欠款: ",
        "Đã trả: " to "已付: ",
        "Thời gian mua: " to "购买时间: ",
        "Hẹn trả: " to "还款日期: ",
        "đơn hàng" to "订单",
        "1 đơn hàng" to "1 个订单",
        "Tiền lãi: " to "利润: ",
        "Bố cục hiển thị: " to "显示布局: ",
        "Dạng lưới G-View" to "网格视图 (G-View)",
        "Dạng danh sách L-View" to "列表视图 (L-View)",
        "Tiếng Anh" to "英语",
        "Tiếng Trung Quốc" to "中文",
        "Liên hệ (Zalo): " to "联系 (Zalo): ",
        "sp" to "单位",
        "Chưa hẹn" to "未定",

        " mặt hàng" to " 个商品",
        " mặt hàng liên quan" to " 个关联商品",
        " mặt hàng thuộc danh mục này)" to " 个商品属于此分类)",
        " đơn hàng" to " 个订单",
        "' không?" to "' 吗？",
        "' không?\n(Có " to "' 吗？\n(有 ",
        "' khỏi giỏ hàng?" to "' 吗？",
        "(Bấm để sửa)" to "(点击修改)",
        "(Ấn vào mặt hàng để chỉnh sửa)" to "(点击商品进行编辑)",
        "- Chuyển khoản chi trả: %s (Khả dụng: %s)" to "- 转账支付: %s (可用: %s)",
        "- Tiền mặt chi trả: %s (Khả dụng: %s)" to "- 现金支付: %s (可用: %s)",
        "Bán công nợ" to "信用销售",
        "Bán hàng" to "收银",
        "Bán lẻ" to "零售收银",
        "Bán nợ" to "信用销售",
        "Báo cáo doanh thu" to "销售报告",
        "Bạn có chắc chắn muốn hoàn tiền cho hóa đơn này không?" to "您确定要对这张账单进行退款吗？",
        "Bạn có chắc chắn muốn hoàn tiền cho hóa đơn này không?\nHành động này sẽ xóa hóa đơn và hoàn lại toàn bộ sản phẩm vào kho hàng." to "您确定要退款此账单吗？该操作将删除账单，并将所有产品退回库存。",
        "Bạn có chắc chắn muốn tắt bán công nợ cho hóa đơn này không?" to "您确定要关闭此账单的信用销售吗？",
        "Bạn có chắc chắn muốn xóa TẤT CẢ các mặt hàng và danh mục không? Hành động này không thể hoàn tác." to "您确定要删除所有的产品和分类吗？此操作无法撤销。",
        "Bạn có chắc chắn muốn xóa TẤT CẢ dữ liệu (mặt hàng, danh mục, hóa đơn...) không? Hành động này không thể hoàn tác." to "您确定要删除所有的数据（产品、分类、账单...）吗？此操作无法撤销。",
        "Bạn có chắc chắn muốn xóa danh mục '" to "您确定要删除分类 '",
        "Bạn có chắc chắn muốn xóa danh mục này? Hành động này sẽ xóa vĩnh viễn khỏi thiết bị!" to "您确定要删除此分类吗？该操作将从设备中永久删除！",
        "Bạn có chắc chắn muốn xóa mặt hàng '" to "您确定要删除商品 '",
        "Bạn có chắc chắn muốn xóa sản phẩm '\${productToRemoveFromCategory?.name}' khỏi danh mục này không?" to "您确定要将产品 '\${productToRemoveFromCategory?.name}' 从此分类中移除吗？",
        "Bạn có chắc chắn muốn xóa sản phẩm '%s' khỏi hóa đơn này?" to "您确定要从此账单中删除产品 '%s' 吗？",
        "Bạn có chắc chắn muốn xóa sản phẩm này? Hành động này sẽ xóa vĩnh viễn khỏi thiết bị!" to "您确定要删除此产品吗？该操作将从设备中永久删除！",
        "Bạn có chắc chắn muốn xóa toàn bộ công nợ của khách hàng %s? Toàn bộ các hóa đơn nợ của khách hàng này sẽ được xóa." to "您确定要清除客户 %s 的所有债务吗？此客户的所有欠款账单都将被删除。",
        "Bạn có chắc chắn muốn xóa tất cả sản phẩm, hóa đơn và danh mục khỏi thiết bị không? Hành động này không thể hoàn tác!" to "您确定要从设备中删除所有产品、账单和分类吗？此操作无法撤销！",
        "Bạn có chắc chắn muốn xóa đơn nhập hàng này? Hành động này sẽ hoàn tác và khôi phục (giảm) số lượng tồn kho tương ứng của các sản phẩm trong đơn." to "您确定要删除此采购订单吗？此操作将撤销并恢复（减少）订单中相应产品的库存数量。",
        "Bản sao lưu " to "备份文件 ",
        "Bảng quản lý" to "管理面板",
        "Bật chi phí phát sinh" to "启用额外费用",
        "Bố cục" to "布局",
        "Chi Tiết Công Nợ" to "债务详情",
        "Chi phí phát sinh" to "额外费用",
        "Chi tiết Hóa đơn" to "账单详情",
        "Chi tiết đơn hàng:" to "订单详情:",
        "Cho phép gởi thông báo hóa đơn và tải hình ảnh sản phẩm" to "允许发送账单通知和加载产品图片",
        "Cho phép gửi thông báo hóa đơn, truy cập lịch và tải hình ảnh sản phẩm" to "允许发送账单通知、访问日历和上传产品图片",
        "Chuyển khoản" to "银行转账",
        "Chưa có bản sao lưu tự động nào (bản đầu tiên sẽ được tạo vào lúc 23:50)." to "暂无自动备份 (第一个备份将在 23:50 创建)。",
        "Chưa có danh mục nào được thiết lập" to "尚未设置任何分类",
        "Chưa có danh mục nào. Nhấp '+' để thêm." to "暂无分类，请点击 '+' 添加。",
        "Chưa có hóa đơn nào được tạo" to "暂无已创建的账单",
        "Chưa có khách hàng nào được lưu lịch sử mua hàng." to "暂无保存购买历史的客户。",
        "Chưa có mặt hàng nào trong đơn" to "订单中尚无商品",
        "Chưa có mặt hàng nào. Nhấn nút + bên dưới để tạo mới." to "暂无商品。点击下方 + 按钮创建。",
        "Chưa có sản phẩm nào. Nhấp '+' để thêm." to "暂无产品，请点击 '+' 添加。",
        "Chưa có đơn nhập hàng nào" to "尚无采购订单",
        "Chưa phân nhóm" to "未分配",
        "Chế độ tối (Dark mode)" to "深色模式",
        "Chỉnh sửa mặt hàng" to "编辑商品",
        "Chỉnh sửa sản phẩm" to "编辑产品",
        "Chỉnh sửa tên danh mục" to "修改分类名称",
        "Chỉnh sửa đơn nhập" to "编辑采购订单",
        "Đồng bộ nhà cung cấp" to "同步供应商",
        "Đồng bộ hóa nhà cung cấp từ các đơn nhập hàng cũ" to "从历史采购订单同步供应商名称",
        "Đồng bộ thành công" to "同步成功",
        "Chọn danh mục" to "选择分类",
        "Chọn hoặc nhập danh mục mới..." to "选择或输入新分类...",
        "Chọn hoặc nhập nhà cung cấp..." to "选择或输入供应商...",
        "Chọn hình ảnh" to "选择图片",
        "Chọn hình ảnh từ Gallery" to "从相册选择图片",
        "Chọn màu sắc hiển thị" to "选择显示颜色",
        "Chọn sản phẩm có sẵn" to "选择已有产品",
        "Chức năng trực tuyến đang được triển khai" to "在线功能正在开发中",
        "Cài đặt" to "设置",
        "Cài đặt hệ thống" to "系统设置",
        "Có " to "有 ",
        "Cảnh báo" to "警告",
        "Cảnh báo đặc biệt nguy hiểm!" to "极度危险区域！",
        "Cấp quyền cho tất cả" to "授予全部权限",
        "Cấp quyền hệ thống" to "系统权限",
        "Cấu hình" to "配置",
        "Cấu hình POS" to "收银台配置",
        "CẬP NHẬT" to "更新",
        "Cập nhật" to "更新",
        "Cập nhật nhanh tồn kho" to "快速更新库存",
        "Cập nhật thông tin" to "更新信息",
        "Cập nhật trực tiếp giá nhập hệ thống:" to "直接更新系统进价:",
        "Cập nhật đơn nhập hàng thành công!" to "采购订单更新成功！",
        "Danh mục" to "分类",
        "Danh mục (mặc định 'Không danh mục')" to "分类 (默认 '未分类')",
        "Danh sách hàng nhập" to "采购商品列表",
        "Danh sách hóa đơn bán hàng" to "销售账单列表",
        "Danh sách mặt hàng:" to "商品列表:",
        "Danh sách đơn hàng nợ:" to "欠款订单列表:",
        "Danh sách đơn hàng đã lấy:" to "已取走的订单列表:",
        "Doanh thu theo sản phẩm" to "按产品销售统计",
        "Doanh thu và lợi nhuận bán hàng" to "销售额与利润",
        "Dọn dẹp dữ liệu" to "数据清理",
        "Giao dịch đã được ghi nhận vào lịch sử." to "该交易已记录到历史中。",
        "Giá bán" to "销售价格",
        "Giá bán sỉ & lẻ thực tế sẽ được hiển thị công khai trên giao diện POS." to "实际批发和零售价格将公开显示在POS界面上。",
        "Giá bán: " to "售价: ",
        "Giá nhập" to "进价",
        "Giá nhập mới" to "新进价",
        "Giá: " to "单价: ",
        "Giỏ hàng" to "购物车",
        "Giỏ hàng của bạn đang trống" to "您的购物车为空",
        "Giỏ hàng hiện có %d mặt hàng" to "购物车当前有 %d 件商品",
        "Giỏ hàng hiện tại đang trống. Vui lòng thêm sản phẩm vào giỏ hàng trước!" to "当前购物车为空。请先添加商品！",
        "Giỏ hàng đang trống" to "购物车为空",
        "Giới thiệu" to "关于",
        "Gán các sản phẩm đã có vào danh mục này:" to "将现有商品分配到此分类:",
        "Gợi ý sản phẩm:" to "推荐产品:",
        "Gợi ý từ đơn hàng trước của nhà cung cấp này:" to "该供应商历史订单 of this supplier's suggested products:",
        "HOÀN THÀNH ĐƠN" to "完成订单",
        "HOÀN TIỀN & HỦY HÓA ĐƠN" to "退款并作废账单",
        "HOÀN TẤT" to "完成",
        "Hoàn tiền" to "退款",
        "Hoàn tiền thành công!" to "退款成功！",
        "Hàng tồn kho" to "库存货量",
        "Hóa đơn" to "账单",
        "Hóa đơn chi tiết" to "详细账单",
        "Hóa đơn đã được lưu trữ trong danh mục lịch sử. Hàng tồn kho đã được tự động khấu trừ." to "账单已存入历史记录，库存已自动扣减。",
        "HỦY" to "取消",
        "Hủy" to "取消",
        "Hủy bỏ" to "取消",
        "Kho hàng:" to "仓库库房:",
        "Khách hàng & Đối tác" to "客户与合作伙伴",
        "Khách hàng:" to "客户:",
        "Khách hàng: " to "客户: ",
        "Khách lẻ" to "散客",
        "Khôi phục" to "恢复",
        "Không" to "不退",
        "Không có khách hàng nào đang nợ." to "目前没有客户欠款。",
        "Không có sản phẩm nào trong danh mục này" to "此分类下无任何产品",
        "Không có sản phẩm nào tồn kho." to "仓库中没有商品。",
        "Không danh mục" to "未分类",
        "Không thể lưu lịch hẹn vì thiếu quyền truy cập lịch." to "因缺少日历访问权限，无法保存约还日程。",
        "Không thể mở trình chọn tệp: " to "无法打开文件选择器: ",
        "Không thể mở trình ghi tệp: " to "无法打开文件写入器: ",
        "Không thể tạo sự kiện lịch" to "无法创建日历日程",
        "Không tìm thấy khách hàng phù hợp." to "未找到匹配的客户。",
        "Không tìm thấy mặt hàng nào để gán." to "未找到可分配的商品。",
        "Không tìm thấy mặt hàng để chỉnh sửa" to "未找到要编辑的商品",
        "Không tìm thấy sản phẩm nào" to "未找到任何产品",
        "Không tìm thấy sản phẩm phù hợp." to "未找到匹配的产品。",
        "Kết quả tìm kiếm:" to "搜索结果:",
        "Liên hệ (Zalo): 0964935879" to "联系方式 (Zalo): 0964935879",
        "LƯU" to "保存",
        "Lưu" to "保存",
        "Lưu danh mục" to "保存分类",
        "Lưu lịch hẹn" to "保存约还日程",
        "Lưu sản phẩm" to "保存产品",
        "Lưu thất bại: " to "保存失败: ",
        "Lập đơn nhập hàng" to "创建采购订单",
        "Lập đơn nhập hàng thành công!" to "采购订单创建成功！",
        "Lịch hẹn thanh toán" to "付款计划日程",
        "Lịch sử hóa đơn" to "历史账单",
        "Lịch sử mua hàng và tìm kiếm khách hàng" to "购买记录与客户搜索",
        "Lịch sử mua sắm" to "购买记录",
        "Lỗ: " to "亏损: ",
        "Lỗi lấy ID sự kiện lịch" to "获取日历日程ID失败",
        "LỢI NHUẬN (TIỀN LÃI):" to "利润 (盈利):",
        "Lợi nhuận: " to "利润: ",
        "Mã HD: #" to "账单编号: #",
        "Mô tả sản phẩm..." to "产品描述...",
        "Mô tả..." to "描述...",
        "Mặt Hàng" to "产品商品",
        "Mở rộng" to "展开",
        "Mục Tra Soát Hóa Đơn" to "账单对账",
        "Nguồn tiền" to "资金来源",
        "Ngôn ngữ (Language)" to "语言",
        "Người sáng lập: Cường lâm" to "创始人: 强林",
        "Nhà cung cấp" to "供应商",
        "Nhà cung cấp ẩn danh" to "匿名供应商",
        "Nhấp để khôi phục nhanh dữ liệu từ bản này" to "点击从此备份中快速恢复数据",
        "Nhập Tên Khách Hàng (Tự động lưu)" to "输入客户名称 (自动保存)",
        "Nhập giá bán" to "输入售价",
        "Nhập giá bán..." to "输入售价...",
        "Nhập giá nhập" to "输入进价",
        "Nhập giá nhập..." to "输入进价...",
        "Nhập gần đây: " to "最近采购: ",
        "Nhập mô tả danh mục..." to "输入分类描述...",
        "Nhập mô tả..." to "输入描述...",
        "Nhập sao lưu" to "导入备份",
        "Nhập số lượng mới" to "输入新数量",
        "Nhập số lượng tồn kho ban đầu..." to "输入初始库存数量...",
        "Nhập số tiền thanh toán" to "输入支付金额",
        "Nhập tên danh mục" to "输入分类名称",
        "Nhập tên khách hàng..." to "输入客户姓名...",
        "Nhập tên mặt hàng..." to "输入商品名称...",
        "Nhập tên mới cho khách hàng %s:" to "为客户 %s 输入新名称:",
        "Nhập tên nhà cung cấp..." to "输入供应商名称...",
        "Nhập tên sản phẩm" to "输入产品名称",
        "Phiên bản 1.3.9" to "版本 1.3.9",
        "Phiên bản: 1.3.9" to "版本: 1.3.9",
        "Phân Loại Danh Mục" to "分类归档",
        "Phân vùng nhóm danh mục hàng hóa để tối ưu hóa việc phân nhóm hiển thị trên POS." to "对商品分类进行分区，以优化POS上的分组显示。",
        "Quyền lịch đã được cấp. Hãy nhấn 'Lưu lịch hẹn' một lần nữa để lưu." to "已授予日历权限。请再次点击 '保存约还日程' 进行保存。",
        "Quản lý" to "管理",
        "Quản lý Danh mục" to "分类管理",
        "Quản lý Khách hàng" to "客户管理",
        "Quản lý Mặt hàng" to "产品管理",
        "Quản lý công nợ" to "债务管理",
        "Quản lý hàng tồn" to "库存管理",
        "Quản lý kho hàng" to "库存管理",
        "Quản lý nhập hàng" to "采购管理",
        "Quản lý và điều phối các kho hàng của bạn" to "管理和协调您的仓库库存",
        "Quản lý đơn nhập hàng, thêm nhà cung cấp, cập nhật giá vốn và số lượng tồn kho." to "管理采购订单、供应商、进价和库存数量。",
        "Sao Lưu Tự Động Hàng Ngày (23:50)" to "每日自动备份 (23:50)",
        "Sao lưu" to "备份",
        "Sao lưu & Khôi phục dữ liệu" to "数据备份与恢复",
        "Sao lưu cơ sở dữ liệu bán hàng đám mây" to "云端销售数据库备份",
        "Sao lưu dữ liệu" to "数据备份",
        "Sao lưu thành công" to "备份成功",
        "Sao lưu toàn bộ dữ liệu có trong ứng dụng không bỏ sót thông tin nào cả (sản phẩm, danh mục, hóa đơn, đơn nhập, cấu hình hệ thống, hình ảnh). Hỗ trợ kích thước tệp tối đa lên tới 800MB." to "完整备份应用程序中的所有数据（产品、分类、账单、采购订单、系统配置、图片）。最大支持 800MB 文件的备份。",
        "SĐT: " to "电话: ",
        "Sản phẩm" to "产品",
        "Sản phẩm sắp hết hàng (< 5)" to "库存紧张产品 (< 5)",
        "Sản phẩm đã hết hàng (0)" to "已售罄产品 (0)",
        "Số lượng" to "数量",
        "Số lượng nhập" to "采购数量",
        "Số lượng phải lớn hơn 0!" to "数量必须大于 0！",
        "Số lượng tồn kho" to "库存数量",
        "Số lượng vượt quá hàng tồn kho! Tự động điều chỉnh về %d" to "数量超过库存数量！已自动调整为 %d",
        "Số tiền chi phí phát sinh" to "额外费用金额",
        "Số tiền thanh toán vượt quá hạn mức khả dụng trong nguồn tiền. Bạn có chắc chắn muốn tiếp tục?" to "支付金额超过了资金来源 of available limit. Are you sure you want to continue?",
        "Số tiền thanh toán vượt quá tổng nợ hiện tại!" to "支付金额超过了当前的总债务！",
        "SỬA ĐƠN" to "编辑订单",
        "Sử dụng ảnh mẫu thiết bị có sẵn" to "使用内置示例图片",
        "Sửa" to "编辑",
        "Sửa Sản Phẩm" to "编辑产品",
        "Sửa nguồn tiền" to "编辑资金来源",
        "Sửa thông tin mặt hàng nhập" to "编辑采购商品信息",
        "Sửa tên khách hàng" to "编辑客户名称",
        "THANH TOÁN Giao Dịch" to "确认结账交易",
        "THÊM" to "添加",
        "Thanh Toán Thành Công!" to "支付成功！",
        "Thanh toán CK" to "转账支付",
        "Thanh toán TM" to "现金支付",
        "Thanh toán thành công!" to "结账成功！",
        "Thanh toán trước" to "提前付款",
        "Theo dõi hàng trong kho" to "跟踪库存",
        "Theo dõi lượng tồn kho từng sản phẩm, đơn giá nhập và tổng giá trị tồn kho toàn hệ thống." to "跟踪每个产品的库存量、进价以及全系统的总库存价值。",
        "Theo dõi tồn kho" to "跟踪库存",
        "Theo dõi và quản lý các đơn hàng bán nợ, danh sách khách hàng nợ và lịch hẹn thanh toán." to "跟踪和管理信用销售、客户债务和付款时间表。",
        "Thu gọn" to "收起",
        "Thành tiền: " to "金额: ",
        "Thêm danh mục" to "添加分类",
        "Thêm danh mục mới" to "添加新分类",
        "Thêm hàng mới" to "添加新商品",
        "Thêm mặt hàng" to "添加商品",
        "Thêm mặt hàng từ giỏ hàng" to "从购物车添加商品",
        "Thêm sản phẩm" to "添加产品",
        "Thêm sản phẩm nhập" to "添加采购产品",
        "Thêm từ giỏ hàng" to "从购物车添加",
        "Thống kê tồn kho" to "库存水平统计",
        "Thời gian:" to "时间:",
        "Tiết kiệm pin và dịu mắt khi sử dụng ban đêm" to "节省电量并在夜间保护眼睛",
        "Tiền mặt" to "现金",
        "Tiền mặt (VND)" to "现金 (VND)",
        "Tiền mặt: " to "现金: ",
        "Tra soát hóa đơn" to "账单对账",
        "Trong kho" to "在库数量",
        "Trạng thái:" to "状态:",
        "Trở về" to "返回",
        "Tài khoản (VND)" to "账户 (VND)",
        "Tài khoản: " to "账户: ",
        "Tên Khách Hàng" to "客户名称",
        "Tên danh mục" to "分类名称",
        "Tên danh mục..." to "分类名称...",
        "Tên khách hàng mới" to "新客户名称",
        "Tên khách hàng..." to "客户名称...",
        "Tên mặt hàng" to "商品名称",
        "Tên mặt hàng *" to "商品名称 *",
        "Tên nhà cung cấp" to "供应商名称",
        "Tên sản phẩm..." to "产品名称...",
        "Tìm kiếm" to "搜索",
        "Tìm kiếm hóa đơn..." to "搜索账单...",
        "Tìm kiếm khách hàng..." to "搜索客户...",
        "Tìm kiếm sản phẩm..." to "搜索产品...",
        "Tìm tên sản phẩm..." to "搜索商品名称...",
        "Tạo Danh Mục" to "创建分类",
        "Tạo Sản Phẩm" to "创建产品",
        "Tạo danh mục" to "创建分类",
        "Tạo mặt hàng" to "创建商品",
        "Tạo mặt hàng mới" to "创建新商品",
        "Tải ảnh sản phẩm" to "上传产品图片",
        "Tất cả" to "全部",
        "Tất cả các quyền cần thiết đã được cấp" to "所有必要的权限已被授予",
        "Tắt bán nợ" to "关闭信用销售",
        "Tệp và Sao Lưu JSON" to "JSON文件与备份",
        "Tối ưu hóa quản lý và tra soát khách hàng" to "优化客户管理与对账",
        "Tổng Doanh Thu Hoạt Động" to "总营业收入",
        "Tổng công nợ" to "总债务",
        "Tổng cộng tiền hàng:" to "总金额:",
        "Tổng cộng:" to "总计:",
        "Tổng giá trị đơn nhập:" to "采购单总价:",
        "Tổng lỗ: " to "总亏损: ",
        "Tổng lợi nhuận thực tế" to "实际总利润",
        "Tổng quan sản phẩm" to "产品总览",
        "Tổng số sản phẩm trong kho" to "库存产品总数",
        "Tổng tiền hàng:" to "商品总额:",
        "Tổng tiền tồn kho" to "总库存金额",
        "Tổng tồn" to "库存总额",
        "Tự động sao lưu" to "自动备份",
        "Tự động tự sao lưu lúc 23:50 hàng ngày. Ghi đè tự động." to "每日23:50自动备份。自动覆盖。",
        "Vui lòng cấp quyền đặt báo thức để sao lưu đúng giờ" to "请授予闹钟权限以保证准时自动备份",
        "Vui lòng nhập số lượng hợp lệ!" to "请输入有效的数量！",
        "Vui lòng nhập số tiền hợp lệ" to "请输入有效的金额",
        "Vui lòng nhập tên danh mục" to "请输入分类名称",
        "Vui lòng nhập tên khách hàng" to "请输入客户名称",
        "Vui lòng nhập tên mặt hàng" to "请输入商品名称",
        "Vui lòng nhập đầy đủ thông tin!" to "请填写所有必填信息！",
        "Vui lòng điền đúng giá trị!" to "请输入有效的数值！",
        "Vui lòng ấn nút + ở góc phải bên dưới để lập đơn hàng nhập mới." to "请点击右下角的 + 按钮创建新的采购订单。",
        "Ví dụ: 50000" to "示例: 50000",
        "Ví dụ: 500000" to "示例: 500000",
        "Xem lịch sử mua hàng, chi tiết các hóa đơn và sản phẩm mà khách hàng đã lấy." to "查看购买历史、账单详情以及客户所购的产品。",
        "Xem, thêm mặt hàng mới, thiết lập giá bán, và cấu hình lượng hàng tồn kho." to "查看、添加新产品、设置售价及配置库存数量。",
        "Xuất hoặc nhập toàn bộ thông tin về sản phẩm, giá cả, tồn kho, ảnh sản phẩm, khách hàng và đơn hàng dưới dạng tệp JSON." to "以JSON文件形式导出或导入关于产品、价格、库存、产品图片、客户和订单的全部信息。",
        "Xuất sao lưu" to "导出备份",
        "XÓA" to "删除",
        "XÓA TOÀN BỘ CƠ SỞ DỮ LIỆU" to "清空全部数据库",
        "XÓA ĐƠN" to "删除订单",
        "Xác nhận" to "确认",
        "Xác nhận hoàn tiền" to "确认退款",
        "Xác nhận tiếp tục" to "确认继续",
        "Xác nhận tắt bán nợ" to "确认关闭信用销售",
        "Xác nhận vượt hạn mức chi trả" to "确认超出限额",
        "Xác nhận xóa" to "确认删除",
        "Xác nhận xóa danh mục" to "确认删除分类",
        "Xác nhận xóa danh mục?" to "确认删除分类吗？",
        "Xác nhận xóa nợ" to "确认清除债务",
        "Xác nhận xóa sản phẩm khỏi danh mục" to "确认从此分类中移除产品",
        "Xác nhận xóa sản phẩm?" to "确认删除产品吗？",
        "Xác nhận xóa tất cả" to "确认清空全部",
        "Xác nhận xóa tất cả dữ liệu" to "确认清空全部数据",
        "Xác thực sao lưu" to "备份验证",
        "Xóa" to "删除",
        "Xóa hết" to "全部删除",
        "Xóa khỏi danh mục" to "从分类中移除",
        "Xóa mặt hàng" to "删除商品",
        "Xóa nợ" to "清除债务",
        "Xóa tìm kiếm" to "清除搜索",
        "Xóa tất cả dữ liệu" to "清空全部数据",
        "Xóa tất cả dữ liệu hiện có khỏi hệ thống (sản phẩm, danh mục, hóa đơn...)" to "从系统中删除所有现有的数据（产品、分类、账单...）",
        "Xóa tất cả mặt hàng & danh mục" to "删除全部产品与分类",
        "Xóa tất cả mặt hàng và danh mục hiện có ra khỏi hệ thống" to "从系统中删除所有现有的产品和分类",
        "mặt hàng" to "商品",
        "Đang sao lưu..." to "正在备份...",
        "Đang thuộc danh mục khác" to "属于其他分类",
        "Điều chỉnh nguồn tiền" to "调整资金来源",
        "Đã cấp quyền hoàn tất" to "权限已完全授予",
        "Đã cập nhật nguồn tiền thành công!" to "资金来源调整成功！",
        "Đã cập nhật sản phẩm!" to "产品已更新！",
        "Đã cập nhật thông tin mặt hàng" to "商品信息已更新",
        "Đã cập nhật tồn kho thành công!" to "库存更新成功！",
        "Đã cập quyền hoàn tất" to "权限已完全授予",
        "Đã hoàn tiền" to "已退款",
        "Đã hoàn trả sản phẩm vào kho và xóa hóa đơn!" to "产品已退回库存，账单已删除！",
        "Đã lưu danh mục mới" to "新分类已保存",
        "Đã lưu danh mục thành công!" to "分类保存成功！",
        "Đã lưu lịch hẹn thanh toán vào lịch máy!" to "还款计划日程已成功保存至设备日历！",
        "Đã lưu mặt hàng mới" to "新商品已保存",
        "Đã lưu sản phẩm thành công!" to "产品保存成功！",
        "Đã thanh toán" to "已付款",
        "Đã thanh toán trước thành công số tiền: " to "成功预付金额: ",
        "Đã thêm các mặt hàng từ giỏ hàng vào hóa đơn!" to "已将购物车中的商品添加至此账单中！",
        "Đã trả hàng và hoàn lại tiền." to "已退货并完成退款。",
        "Đã xóa sản phẩm khỏi hóa đơn!" to "已从账单中删除产品！",
        "Đã xóa toàn bộ công nợ thành công!" to "清除所有债务成功！",
        "Đã xóa toàn bộ dữ liệu" to "已清空全部数据",
        "Đã xóa toàn bộ sản phẩm và danh mục" to "已清空全部产品和分类",
        "Đã xóa đơn nhập hàng và cập nhật lại tồn kho" to "已删除采购订单并重新更新库存",
        "Đã đến lịch thanh toán của " to "到期还款安排 - ",
        "Đã đổi thành " to "已更改为 ",
        "Đóng" to "关闭",
        "Đăng nhập hoặc Đăng ký" to "登录或注册",
        "Đăng nhập tài khoản" to "账户登录",
        "Đơn" to "订单",
        "Đơn giá:" to "单价:",
        "Đại diện trên POS" to "POS展示图",
        "Ảnh sản phẩm" to "产品图片",
        "Để đảm bảo an toàn cho dữ liệu bán hàng của bạn, vui lòng thực hiện sao lưu trước khi tiến hành xóa toàn bộ dữ liệu khỏi hệ thống." to "为了确保销售数据的安全，在继续删除系统所有数据之前，请先执行数据备份。",
        "Lập báo cáo" to "生成报告",
        "Từ ngày" to "起始日期",
        "Đến ngày" to "截止日期",
        "Kết quả báo cáo" to "报告结果",
        "Chọn nhà cung cấp" to "选择供应商",
        "Tổng đơn nhập" to "总采购订单",
        "Tổng tiền nhập" to "总采购金额",
        "lập báo cáo nhập hàng" to "创建采购报告",
        "Tổng đơn hàng" to "订单总数",
        "Tổng doanh thu" to "总营业额",
        "Tổng lỗ" to "总亏损",
        "Bạn đang có mặt hàng trong đơn nhập. Bạn có muốn lưu nháp đơn hàng này không?" to "您进货单中有商品。您想将此订单保存为草稿吗？",
        "Lưu nháp" to "保存草稿",
        "Thoát" to "退出",
        "NHÁP" to "草稿",
        "HOÀN THÀNH" to "完成",
        "Đã lưu nháp đơn nhập hàng!" to "进货单已保存为草稿！",
        "Đã xác nhận hoàn thành đơn nhập hàng!" to "进货单完成已确认！",
        "Căn chỉnh ảnh sản phẩm" to "调整商品图片",
        "Di chuyển hoặc phóng to/thu nhỏ ảnh để vừa khung hình 1:1" to "移动或缩放图片以契合 1:1 正方形框",
        "Lỗi lưu ảnh đã cắt" to "保存裁剪的图片出错",
        "Lỗi cắt ảnh" to "裁剪图片出错",
        "Không thể tải hình ảnh" to "无法加载图片",
        "Thu phóng" to "缩放",
        "Xoay 90°" to "旋转 90°",
        "Hoàn hàng" to "退货",
        "Hàng tồn:" to "库存:",
        "Tính toán tiền hoàn lại:" to "计算退款金额:",
        "Xác nhận hoàn hàng" to "确认退货",
        "Bạn có chắc chắn muốn hoàn" to "您确定要退货",
        "sản phẩm với tổng số tiền là" to "件商品，总金额为",
        "không?\n\nHệ thống sẽ tự động trừ kho và cộng lại tiền mặt." to "吗？\n\n系统将自动扣减库存并退还现金。",
        "Số lượng hoàn" to "退货数量"
    )

    private val americanMap = mapOf(
        "Tồn kho từ nhiều đến ít" to "Stock: High to Low",
        "Tổng tồn từ thấp đến cao" to "Total stock: Low to High",
        "Tổng tồn từ cao đến thấp" to "Total stock: High to Low",
        "Chọn phương thức thanh toán" to "Select payment method",
        "Tiền mặt" to "Cash",
        "Chuyển khoản" to "Transfer",
        "Tên sản phẩm" to "Product Name",
        "SL" to "Qty",
        "Đơn giá" to "Price",
        "Thành tiền" to "Total",
        "Tồn còn lại: " to "Remaining stock: ",
        " mặt hàng" to " items",
        " mặt hàng liên quan" to " related items",
        " mặt hàng thuộc danh mục này)" to " items in this category)",
        " đơn hàng" to " orders",
        "' không?" to "'?",
        "' không?\n(Có " to "'?\n(There are ",
        "' khỏi giỏ hàng?" to "' from the cart?",
        "(Bấm để sửa)" to "(Tap to edit)",
        "(Ấn vào mặt hàng để chỉnh sửa)" to "(Tap on item to edit)",
        "- Chuyển khoản chi trả: %s (Khả dụng: %s)" to "- Bank transfer paid: %s (Available: %s)",
        "- Tiền mặt chi trả: %s (Khả dụng: %s)" to "- Cash paid: %s (Available: %s)",
        "Bán công nợ" to "Sell on credit",
        "Bán hàng" to "POS",
        "Bán lẻ" to "Retail POS",
        "Bán nợ" to "Sell on credit",
        "Bán: " to "Sell: ",
        "Báo cáo doanh thu" to "Sales Report",
        "Bạn có chắc chắn muốn hoàn tiền cho hóa đơn này không?" to "Are you sure you want to refund this receipt?",
        "Bạn có chắc chắn muốn hoàn tiền cho hóa đơn này không?\nHành động này sẽ xóa hóa đơn và hoàn lại toàn bộ sản phẩm vào kho hàng." to "Are you sure you want to refund this invoice?\nThis will delete the invoice and return all products to inventory.",
        "Bạn có chắc chắn muốn tắt bán công nợ cho hóa đơn này không?" to "Are you sure you want to disable selling on credit for this invoice?",
        "Bạn có chắc chắn muốn xóa TẤT CẢ các mặt hàng và danh mục không? Hành động này không thể hoàn tác." to "Are you sure you want to delete ALL products and categories? This cannot be undone.",
        "Bạn có chắc chắn muốn xóa TẤT CẢ dữ liệu (mặt hàng, danh mục, hóa đơn...) không? Hành động này không thể hoàn tác." to "Are you sure you want to delete ALL data (products, categories, invoices...)? This cannot be undone.",
        "Bạn có chắc chắn muốn xóa danh mục '" to "Are you sure you want to delete category '",
        "Bạn có chắc chắn muốn xóa danh mục này? Hành động này sẽ xóa vĩnh viễn khỏi thiết bị!" to "Are you sure you want to delete this category? This cannot be undone!",
        "Bạn có chắc chắn muốn xóa mặt hàng '" to "Are you sure you want to delete '",
        "Bạn có chắc chắn muốn xóa sản phẩm '\${productToRemoveFromCategory?.name}' khỏi danh mục này không?" to "Are you sure you want to remove the product '\${productToRemoveFromCategory?.name}' from this category?",
        "Bạn có chắc chắn muốn xóa sản phẩm '%s' khỏi hóa đơn này?" to "Are you sure you want to delete product '%s' from this invoice?",
        "Bạn có chắc chắn muốn xóa sản phẩm này? Hành động này sẽ xóa vĩnh viễn khỏi thiết bị!" to "Are you sure you want to delete this product? This cannot be undone!",
        "Bạn có chắc chắn muốn xóa toàn bộ công nợ của khách hàng %s? Toàn bộ các hóa đơn nợ của khách hàng này sẽ được xóa." to "Are you sure you want to clear all debts of customer %s? All credit invoices of this customer will be deleted.",
        "Bạn có chắc chắn muốn xóa tất cả sản phẩm, hóa đơn và danh mục khỏi thiết bị không? Hành động này không thể hoàn tác!" to "Are you sure you want to delete all products, receipts, and categories? This cannot be undone!",
        "Bạn có chắc chắn muốn xóa đơn nhập hàng này? Hành động này sẽ hoàn tác và khôi phục (giảm) số lượng tồn kho tương ứng của các sản phẩm trong đơn." to "Are you sure you want to delete this purchase order? This action will undo and restore (reduce) the corresponding inventory stock of products in the order.",
        "Bản sao lưu " to "Backup ",
        "Bảng quản lý" to "Management Board",
        "Bật chi phí phát sinh" to "Enable additional costs",
        "Bố cục" to "Layout",
        "Bố cục hiển thị: " to "Layout View: ",
        "Chi Tiết Công Nợ" to "Debt Details",
        "Chi phí phát sinh" to "Additional Costs",
        "Chi tiết Hóa đơn" to "Receipt Details",
        "Chi tiết đơn hàng:" to "Order details:",
        "Cho phép gởi thông báo hóa đơn và tải hình ảnh sản phẩm" to "Allow notifications and photo uploads",
        "Cho phép gửi thông báo hóa đơn, truy cập lịch và tải hình ảnh sản phẩm" to "Allow invoice notifications, calendar access, and product image uploads",
        "Chuyển khoản" to "Bank Transfer",
        "Chưa có bản sao lưu tự động nào (bản đầu tiên sẽ được tạo vào lúc 23:50)." to "No auto-backups yet (the first will be created at 23:50).",
        "Chưa có danh mục nào được thiết lập" to "No categories set up yet",
        "Chưa có danh mục nào. Nhấp '+' để thêm." to "No categories yet. Click '+' to add.",
        "Chưa có hóa đơn nào được tạo" to "No receipts created yet",
        "Chưa có khách hàng nào được lưu lịch sử mua hàng." to "No customer purchase histories found.",
        "Chưa có mặt hàng nào trong đơn" to "No items in the order yet",
        "Chưa có mặt hàng nào. Nhấn nút + bên dưới để tạo mới." to "No products yet. Click + below to create one.",
        "Chưa có sản phẩm nào. Nhấp '+' để thêm." to "No products yet. Click '+' to add.",
        "Chưa có đơn nhập hàng nào" to "No purchase orders yet",
        "Chưa hẹn" to "Not scheduled",
        "Chưa phân nhóm" to "Unassigned",
        "Chế độ tối (Dark mode)" to "Dark Mode",
        "Chỉnh sửa mặt hàng" to "Edit Product",
        "Chỉnh sửa sản phẩm" to "Edit product",
        "Chỉnh sửa tên danh mục" to "Edit category name",
        "Chỉnh sửa đơn nhập" to "Edit purchase order",
        "Đồng bộ nhà cung cấp" to "Sync suppliers",
        "Đồng bộ hóa nhà cung cấp từ các đơn nhập hàng cũ" to "Sync supplier names from past import orders",
        "Đồng bộ thành công" to "Synced successfully",
        "Chọn danh mục" to "Category",
        "Chọn hoặc nhập danh mục mới..." to "Select or enter new category...",
        "Chọn hoặc nhập nhà cung cấp..." to "Select or enter supplier...",
        "Chọn hình ảnh" to "Choose image",
        "Chọn hình ảnh từ Gallery" to "Select image from Gallery",
        "Chọn màu sắc hiển thị" to "Category Color Accent",
        "Chọn sản phẩm có sẵn" to "Select existing product",
        "Chức năng trực tuyến đang được triển khai" to "Online features coming soon",
        "Cài đặt" to "Settings",
        "Cài đặt hệ thống" to "System Settings",
        "Còn nợ: " to "Remaining debt: ",
        "Có " to "There are ",
        "Cảnh báo" to "Warning",
        "Cảnh báo đặc biệt nguy hiểm!" to "Danger Zone!",
        "Cấp quyền cho tất cả" to "Grant All Permissions",
        "Cấp quyền hệ thống" to "System Permissions",
        "Cấu hình" to "Configure",
        "Cấu hình POS" to "POS Config",
        "CẬP NHẬT" to "UPDATE",
        "Cập nhật" to "Update",
        "Cập nhật nhanh tồn kho" to "Quick Qty Adjust",
        "Cập nhật thông tin" to "Update Info",
        "Cập nhật trực tiếp giá nhập hệ thống:" to "Directly update system cost price:",
        "Cập nhật đơn nhập hàng thành công!" to "Purchase order updated successfully!",
        "Danh mục" to "Categories",
        "Danh mục (mặc định 'Không danh mục')" to "Category (default 'Uncategorized')",
        "Danh sách hàng nhập" to "List of purchased goods",
        "Danh sách hóa đơn bán hàng" to "Transaction Receipts",
        "Danh sách mặt hàng:" to "Item List:",
        "Danh sách đơn hàng nợ:" to "List of credit orders:",
        "Danh sách đơn hàng đã lấy:" to "Purchased order list:",
        "Doanh thu theo sản phẩm" to "Sales by Product",
        "Doanh thu và lợi nhuận bán hàng" to "Revenue & Profit",
        "Dạng danh sách L-View" to "List View",
        "Dạng lưới G-View" to "Grid View",
        "Dọn dẹp dữ liệu" to "Clean Up Data",
        "Giao dịch đã được ghi nhận vào lịch sử." to "The transaction has been saved.",
        "Giá bán" to "Selling price",
        "Giá bán sỉ & lẻ thực tế sẽ được hiển thị công khai trên giao diện POS." to "The actual wholesale & retail prices will be displayed publicly on the POS.",
        "Giá bán: " to "Sell price: ",
        "Giá nhập" to "Import Price",
        "Giá nhập mới" to "New cost price",
        "Giá nhập: " to "Import cost: ",
        "Giá: " to "Price: ",
        "Giỏ hàng" to "Cart",
        "Giỏ hàng của bạn đang trống" to "Your shopping cart is empty",
        "Giỏ hàng hiện có %d mặt hàng" to "Cart has %d items",
        "Giỏ hàng hiện tại đang trống. Vui lòng thêm sản phẩm vào giỏ hàng trước!" to "The cart is empty. Please add products first!",
        "Giỏ hàng đang trống" to "Cart is empty",
        "Giới thiệu" to "About",
        "Giờ: " to "Time: ",
        "Gán các sản phẩm đã có vào danh mục này:" to "Assign existing products to this category:",
        "Gợi ý sản phẩm:" to "Suggested products:",
        "Gợi ý từ đơn hàng trước của nhà cung cấp này:" to "Suggestions from this supplier's previous orders:",
        "HOÀN THÀNH ĐƠN" to "COMPLETE ORDER",
        "HOÀN TIỀN & HỦY HÓA ĐƠN" to "REFUND & CANCEL INVOICE",
        "HOÀN TẤT" to "DONE",
        "Hoàn tiền" to "Refund",
        "Hoàn tiền thành công!" to "Refund Completed!",
        "Hàng tồn kho" to "Inventory",
        "Hóa đơn" to "Receipts",
        "Hóa đơn chi tiết" to "Detailed Receipt",
        "Hóa đơn đã được lưu trữ trong danh mục lịch sử. Hàng tồn kho đã được tự động khấu trừ." to "Invoice archived in history. Inventory has been automatically deducted.",
        "Hẹn trả gần nhất: " to "Nearest due date: ",
        "Hẹn trả: " to "Due date: ",
        "HỦY" to "CANCEL",
        "Hủy" to "Cancel",
        "Hủy bỏ" to "Cancel",
        "Kho hàng:" to "Inventory:",
        "Khác" to "Other",
        "Khách hàng & Đối tác" to "Customers & History",
        "Khách hàng:" to "Customer:",
        "Khách hàng: " to "Customer: ",
        "Khách lẻ" to "Walk-in customer",
        "Khôi phục" to "Restore",
        "Không" to "No",
        "Không có khách hàng nào đang nợ." to "No customers currently have outstanding debt.",
        "Không có sản phẩm nào trong danh mục này" to "No products in this category",
        "Không có sản phẩm nào tồn kho." to "No products in inventory.",
        "Không danh mục" to "Uncategorized",
        "Không thể lưu lịch hẹn vì thiếu quyền truy cập lịch." to "Cannot save schedule due to missing calendar permissions.",
        "Không thể mở trình chọn tệp: " to "Cannot open file picker: ",
        "Không thể mở trình ghi tệp: " to "Cannot open file writer: ",
        "Không thể tạo sự kiện lịch" to "Cannot create calendar event",
        "Không tìm thấy khách hàng phù hợp." to "No matching customers found.",
        "Không tìm thấy mặt hàng nào để gán." to "No products found to assign.",
        "Không tìm thấy mặt hàng để chỉnh sửa" to "Product to edit not found",
        "Không tìm thấy sản phẩm nào" to "No products found",
        "Không tìm thấy sản phẩm phù hợp." to "No matching products found.",
        "Kết quả tìm kiếm:" to "Search results:",
        "Liên hệ (Zalo): " to "Contact (Zalo): ",
        "Liên hệ (Zalo): 0964935879" to "Contact (Zalo): 0964935879",
        "Lãi: " to "Profit: ",
        "LƯU" to "SAVE",
        "Lưu" to "Save",
        "Lưu danh mục" to "Save",
        "Lưu lịch hẹn" to "Save Schedule",
        "Lưu sản phẩm" to "Save",
        "Lưu thất bại: " to "Save failed: ",
        "Lập đơn nhập hàng" to "Create Purchase Order",
        "Lập đơn nhập hàng thành công!" to "Purchase order created successfully!",
        "Lịch hẹn thanh toán" to "Payment Schedule",
        "Lịch sử hóa đơn" to "Receipt History",
        "Lịch sử mua hàng và tìm kiếm khách hàng" to "Purchase history and customer search",
        "Lịch sử mua sắm" to "Purchase History",
        "Lỗ: " to "Loss: ",
        "Lỗi lấy ID sự kiện lịch" to "Error retrieving calendar event ID",
        "LỢI NHUẬN (TIỀN LÃI):" to "PROFIT (EARNINGS):",
        "Lợi nhuận: " to "Profit: ",
        "Mã HD: #" to "Inv Code: #",
        "Mã hóa đơn: " to "Invoice ID: ",
        "Mô tả sản phẩm..." to "Product description...",
        "Mô tả..." to "Description...",
        "Mặt Hàng" to "Products",
        "Mở rộng" to "Expand",
        "Mục Tra Soát Hóa Đơn" to "Invoice Reconciliation",
        "Nguồn tiền" to "Funds Source",
        "Ngôn ngữ (Language)" to "Language",
        "Người sáng lập: Cường lâm" to "Founder: Cuong Lam",
        "Nhà cung cấp" to "Supplier",
        "Nhà cung cấp ẩn danh" to "Anonymous Supplier",
        "Nhấp để khôi phục nhanh dữ liệu từ bản này" to "Click to quickly restore from this backup",
        "Nhập Tên Khách Hàng (Tự động lưu)" to "Customer Name (Auto-saves)",
        "Nhập giá bán" to "Sell Price",
        "Nhập giá bán..." to "Sell price...",
        "Nhập giá nhập" to "Import Price",
        "Nhập giá nhập..." to "Import price...",
        "Nhập gần đây: " to "Recently imported: ",
        "Nhập mô tả danh mục..." to "Description...",
        "Nhập mô tả..." to "Description...",
        "Nhập sao lưu" to "Import",
        "Nhập số lượng mới" to "New Qty",
        "Nhập số lượng tồn kho ban đầu..." to "Initial stock...",
        "Nhập số tiền thanh toán" to "Enter payment amount",
        "Nhập tên danh mục" to "Category Name",
        "Nhập tên khách hàng..." to "Enter customer name...",
        "Nhập tên mặt hàng..." to "Enter product name...",
        "Nhập tên mới cho khách hàng %s:" to "Enter new name for customer %s:",
        "Nhập tên nhà cung cấp..." to "Enter supplier name...",
        "Nhập tên sản phẩm" to "Product Name",
        "Nhập: " to "Import: ",
        "Phiên bản 1.3.9" to "Version 1.3.9",
        "Phiên bản: 1.3.9" to "Version: 1.3.9",
        "Phân Loại Danh Mục" to "Categories",
        "Phân vùng nhóm danh mục hàng hóa để tối ưu hóa việc phân nhóm hiển thị trên POS." to "Organize product categories to optimize POS displays.",
        "Quyền lịch đã được cấp. Hãy nhấn 'Lưu lịch hẹn' một lần nữa để lưu." to "Calendar permission granted. Tap 'Save Schedule' again to save.",
        "Quản lý" to "Manager",
        "Quản lý Danh mục" to "Category Management",
        "Quản lý Khách hàng" to "Customer Management",
        "Quản lý Mặt hàng" to "Product Management",
        "Quản lý công nợ" to "Debt Management",
        "Quản lý hàng tồn" to "Inventory Management",
        "Quản lý kho hàng" to "Inventory Manager",
        "Quản lý nhập hàng" to "Purchase Management",
        "Quản lý và điều phối các kho hàng của bạn" to "Manage and track your warehouse",
        "Quản lý đơn nhập hàng, thêm nhà cung cấp, cập nhật giá vốn và số lượng tồn kho." to "Manage purchase orders, suppliers, cost prices, and inventory stock.",
        "Sao Lưu Tự Động Hàng Ngày (23:50)" to "Daily Auto Backup (11:50 PM)",
        "Sao lưu" to "Backup",
        "Sao lưu & Khôi phục dữ liệu" to "Backup & Restore Data",
        "Sao lưu cơ sở dữ liệu bán hàng đám mây" to "Cloud Database Backup",
        "Sao lưu dữ liệu" to "Backup Data",
        "Sao lưu thành công" to "Backup completed",
        "Sao lưu toàn bộ dữ liệu có trong ứng dụng không bỏ sót thông tin nào cả (sản phẩm, danh mục, hóa đơn, đơn nhập, cấu hình hệ thống, hình ảnh). Hỗ trợ kích thước tệp tối đa lên tới 800MB." to "Backup all data in the application completely (products, categories, invoices, purchase orders, system config, images). Supports file size up to 800MB.",
        "SĐT: " to "Phone: ",
        "Sản phẩm" to "Products",
        "Sản phẩm sắp hết hàng (< 5)" to "Low stock items (< 5)",
        "Sản phẩm đã hết hàng (0)" to "Out of stock (0)",
        "Số lượng" to "Quantity",
        "Số lượng nhập" to "Purchase Quantity",
        "Số lượng phải lớn hơn 0!" to "Quantity must be greater than 0!",
        "Số lượng tồn kho" to "Stock Qty",
        "Số lượng vượt quá hàng tồn kho! Tự động điều chỉnh về %d" to "Quantity exceeds stock! Automatically adjusted to %d",
        "Số lượng: " to "Qty: ",
        "Số tiền chi phí phát sinh" to "Additional cost amount",
        "Số tiền thanh toán vượt quá hạn mức khả dụng trong nguồn tiền. Bạn có chắc chắn muốn tiếp tục?" to "Payment amount exceeds the available limit in the funds source. Are you sure you want to continue?",
        "Số tiền thanh toán vượt quá tổng nợ hiện tại!" to "Payment amount exceeds the current total debt!",
        "SỬA ĐƠN" to "EDIT ORDER",
        "Sử dụng ảnh mẫu thiết bị có sẵn" to "Use placeholder",
        "Sửa" to "Edit",
        "Sửa Sản Phẩm" to "Edit Product",
        "Sửa nguồn tiền" to "Edit Funds Source",
        "Sửa thông tin mặt hàng nhập" to "Edit imported product info",
        "Sửa tên khách hàng" to "Edit customer name",
        "THANH TOÁN Giao Dịch" to "CHECKOUT NOW",
        "THÊM" to "ADD",
        "Thanh Toán Thành Công!" to "Payment Successful!",
        "Thanh toán CK" to "Bank Transfer Pay",
        "Thanh toán TM" to "Cash Pay",
        "Thanh toán thành công!" to "Transaction Completed!",
        "Thanh toán trước" to "Pay in Advance",
        "Theo dõi hàng trong kho" to "Track stock",
        "Theo dõi lượng tồn kho từng sản phẩm, đơn giá nhập và tổng giá trị tồn kho toàn hệ thống." to "Track inventory quantity, cost prices, and total system stock value.",
        "Theo dõi tồn kho" to "Track Inventory",
        "Theo dõi và quản lý các đơn hàng bán nợ, danh sách khách hàng nợ và lịch hẹn thanh toán." to "Track and manage sales on credit, customer debts, and payment schedules.",
        "Thu gọn" to "Collapse",
        "Thành tiền: " to "Subtotal: ",
        "Thêm danh mục" to "Add Category",
        "Thêm danh mục mới" to "Add New Category",
        "Thêm hàng mới" to "Add New Product",
        "Thêm mặt hàng" to "Add Product",
        "Thêm mặt hàng từ giỏ hàng" to "Add items from cart",
        "Thêm sản phẩm" to "Add Product",
        "Thêm sản phẩm nhập" to "Add purchased product",
        "Thêm từ giỏ hàng" to "Add from cart",
        "Thống kê tồn kho" to "Stock Statistics",
        "Thời gian mua: " to "Purchase Time: ",
        "Thời gian:" to "Date & Time:",
        "Tiết kiệm pin và dịu mắt khi sử dụng ban đêm" to "Saves battery and reduces eye strain",
        "Tiền lãi: " to "Profit: ",
        "Tiền mặt" to "Cash",
        "Tiền mặt (VND)" to "Cash (VND)",
        "Tiền mặt: " to "Cash: ",
        "Tra soát hóa đơn" to "Invoice Reconciliation",
        "Trong kho" to "In stock",
        "Trạng thái:" to "Status:",
        "Trở về" to "Back",
        "Tài khoản (VND)" to "Account (VND)",
        "Tài khoản: " to "Account: ",
        "Tên Khách Hàng" to "Customer Name",
        "Tên danh mục" to "Category Name",
        "Tên danh mục..." to "Category name...",
        "Tên khách hàng mới" to "New customer name",
        "Tên khách hàng..." to "Customer name...",
        "Tên mặt hàng" to "Product Name",
        "Tên mặt hàng *" to "Product Name *",
        "Tên nhà cung cấp" to "Supplier Name",
        "Tên sản phẩm..." to "Product name...",
        "Tìm kiếm" to "Search",
        "Tìm kiếm hóa đơn..." to "Search receipts...",
        "Tìm kiếm khách hàng..." to "Search customers...",
        "Tìm kiếm sản phẩm..." to "Search...",
        "Tìm tên sản phẩm..." to "Search product name...",
        "Tạo Danh Mục" to "Create Category",
        "Tạo Sản Phẩm" to "Create Product",
        "Tạo danh mục" to "Create Category",
        "Tạo mặt hàng" to "Create Product",
        "Tạo mặt hàng mới" to "Create new product",
        "Tải ảnh sản phẩm" to "Upload Photo",
        "Tất cả" to "All",
        "Tất cả các quyền cần thiết đã được cấp" to "All required permissions have been granted",
        "Tắt bán nợ" to "Disable selling on credit",
        "Tệp và Sao Lưu JSON" to "JSON Files & Backups",
        "Tối ưu hóa quản lý và tra soát khách hàng" to "Optimize management and tracking",
        "Tồn kho: " to "Stock: ",
        "Tồn: " to "Stock: ",
        "Tổng Doanh Thu Hoạt Động" to "Total Sales Revenue",
        "Tổng công nợ" to "Total Debt",
        "Tổng cộng tiền hàng:" to "Total:",
        "Tổng cộng:" to "Total:",
        "Tổng giá trị đơn nhập:" to "Total Purchase Value:",
        "Tổng lãi" to "Total Profit",
        "Tổng lãi: " to "Total profit: ",
        "Tổng lỗ: " to "Total Loss: ",
        "Tổng lợi nhuận thực tế" to "Actual Total Profit",
        "Tổng quan sản phẩm" to "Product Overview",
        "Tổng số hóa đơn nợ: " to "Total credit invoices: ",
        "Tổng số sản phẩm trong kho" to "Total items in stock",
        "Tổng tiền hàng:" to "Total Amount:",
        "Tổng tiền nợ: " to "Total debt amount: ",
        "Tổng tiền tồn kho" to "Total Inventory Value",
        "Tổng tồn" to "Total Stock Value",
        "Tự động sao lưu" to "Auto Backup",
        "Tự động tự sao lưu lúc 23:50 hàng ngày. Ghi đè tự động." to "Auto backup daily at 23:50. Auto-overwrite.",
        "Vui lòng cấp quyền đặt báo thức để sao lưu đúng giờ" to "Please grant alarm permission to enable scheduled backups",
        "Vui lòng nhập số lượng hợp lệ!" to "Please enter a valid quantity!",
        "Vui lòng nhập số tiền hợp lệ" to "Please enter a valid amount",
        "Vui lòng nhập tên danh mục" to "Please enter category name",
        "Vui lòng nhập tên khách hàng" to "Please enter a customer name",
        "Vui lòng nhập tên mặt hàng" to "Please enter product name",
        "Vui lòng nhập đầy đủ thông tin!" to "Please fill out all fields!",
        "Vui lòng điền đúng giá trị!" to "Please enter valid numbers!",
        "Vui lòng ấn nút + ở góc phải bên dưới để lập đơn hàng nhập mới." to "Please press the + button at the bottom right to create a new purchase order.",
        "Ví dụ: 50000" to "Example: 50000",
        "Ví dụ: 500000" to "Example: 500000",
        "Vốn: " to "Cost: ",
        "Xem lịch sử mua hàng, chi tiết các hóa đơn và sản phẩm mà khách hàng đã lấy." to "View purchase histories, receipt details, and bought products.",
        "Xem, thêm mặt hàng mới, thiết lập giá bán, và cấu hình lượng hàng tồn kho." to "View, add products, set prices, and configure stock.",
        "Xuất hoặc nhập toàn bộ thông tin về sản phẩm, giá cả, tồn kho, ảnh sản phẩm, khách hàng và đơn hàng dưới dạng tệp JSON." to "Export or import all product, price, stock, image, customer and order data as JSON file.",
        "Xuất sao lưu" to "Export",
        "XÓA" to "DELETE",
        "XÓA TOÀN BỘ CƠ SỞ DỮ LIỆU" to "DELETE ALL DATA",
        "XÓA ĐƠN" to "DELETE ORDER",
        "Xác nhận" to "Confirm",
        "Xác nhận hoàn tiền" to "Confirm Refund",
        "Xác nhận tiếp tục" to "Confirm to continue",
        "Xác nhận tắt bán nợ" to "Confirm disabling credit sales",
        "Xác nhận vượt hạn mức chi trả" to "Confirm exceeding limit",
        "Xác nhận xóa" to "Confirm deletion",
        "Xác nhận xóa danh mục" to "Confirm Delete Category",
        "Xác nhận xóa danh mục?" to "Confirm Delete Category?",
        "Xác nhận xóa nợ" to "Confirm debt clearing",
        "Xác nhận xóa sản phẩm khỏi danh mục" to "Confirm removing product from category",
        "Xác nhận xóa sản phẩm?" to "Confirm Delete Product?",
        "Xác nhận xóa tất cả" to "Confirm Delete All",
        "Xác nhận xóa tất cả dữ liệu" to "Confirm Delete All Data",
        "Xác thực sao lưu" to "Verify Backup",
        "Xóa" to "Delete",
        "Xóa hết" to "Delete All",
        "Xóa khỏi danh mục" to "Remove from category",
        "Xóa mặt hàng" to "Delete Product",
        "Xóa nợ" to "Clear debt",
        "Xóa tìm kiếm" to "Clear search",
        "Xóa tất cả dữ liệu" to "Delete All Data",
        "Xóa tất cả dữ liệu hiện có khỏi hệ thống (sản phẩm, danh mục, hóa đơn...)" to "Delete all existing data from system (products, categories, invoices...)",
        "Xóa tất cả mặt hàng & danh mục" to "Delete All Products & Categories",
        "Xóa tất cả mặt hàng và danh mục hiện có ra khỏi hệ thống" to "Delete all existing products and categories from system",
        "mặt hàng" to "items",
        "sp" to "pcs",
        "Đang sao lưu..." to "Backing up...",
        "Đang thuộc danh mục khác" to "In another category",
        "Điều chỉnh nguồn tiền" to "Adjust funds source",
        "Đã cấp quyền hoàn tất" to "Permissions granted successfully",
        "Đã cập nhật nguồn tiền thành công!" to "Funds source adjusted successfully!",
        "Đã cập nhật sản phẩm!" to "Product updated!",
        "Đã cập nhật thông tin mặt hàng" to "Product updated successfully",
        "Đã cập nhật tồn kho thành công!" to "Inventory updated successfully!",
        "Đã cập quyền hoàn tất" to "Permissions granted successfully",
        "Đã hoàn tiền" to "Refunded",
        "Đã hoàn trả sản phẩm vào kho và xóa hóa đơn!" to "Returned products to stock and deleted invoice!",
        "Đã lưu danh mục mới" to "New category saved",
        "Đã lưu danh mục thành công!" to "Category saved successfully!",
        "Đã lưu lịch hẹn thanh toán vào lịch máy!" to "Payment schedule saved to device calendar!",
        "Đã lưu mặt hàng mới" to "New product saved",
        "Đã lưu sản phẩm thành công!" to "Product saved successfully!",
        "Đã thanh toán" to "Paid",
        "Đã thanh toán trước thành công số tiền: " to "Successfully pre-paid: ",
        "Đã thêm các mặt hàng từ giỏ hàng vào hóa đơn!" to "Added items from cart to the invoice!",
        "Đã trả hàng và hoàn lại tiền." to "Returned and refunded.",
        "Đã trả: " to "Paid: ",
        "Đã xóa sản phẩm khỏi hóa đơn!" to "Product deleted from invoice!",
        "Đã xóa toàn bộ công nợ thành công!" to "Cleared all debts successfully!",
        "Đã xóa toàn bộ dữ liệu" to "All data deleted successfully",
        "Đã xóa toàn bộ sản phẩm và danh mục" to "Deleted all products and categories",
        "Đã xóa đơn nhập hàng và cập nhật lại tồn kho" to "Deleted purchase order and restored inventory",
        "Đã đến lịch thanh toán của " to "Payment schedule is due for ",
        "Đã đổi thành " to "Switched to ",
        "Đóng" to "Close",
        "Đăng nhập hoặc Đăng ký" to "Log In or Sign Up",
        "Đăng nhập tài khoản" to "Log In",
        "Đơn" to "Order",
        "Đơn giá:" to "Unit price:",
        "Đơn hàng nợ: " to "Credit order: ",
        "Đại diện trên POS" to "POS Representation",
        "Ảnh sản phẩm" to "Product Image",
        "Để đảm bảo an toàn cho dữ liệu bán hàng của bạn, vui lòng thực hiện sao lưu trước khi tiến hành xóa toàn bộ dữ liệu khỏi hệ thống." to "To ensure the safety of your sales data, please perform a backup before proceeding with deleting all system data.",
        "Lập báo cáo" to "Generate Report",
        "Từ ngày" to "From Date",
        "Đến ngày" to "To Date",
        "Kết quả báo cáo" to "Report Results",
        "Chọn nhà cung cấp" to "Select Supplier",
        "Tổng đơn nhập" to "Total import orders",
        "Tổng tiền nhập" to "Total import amount",
        "lập báo cáo nhập hàng" to "create import report",
        "Tổng đơn hàng" to "Total Orders",
        "Tổng doanh thu" to "Total Revenue",
        "Tổng lỗ" to "Total Loss",
        "Bạn đang có mặt hàng trong đơn nhập. Bạn có muốn lưu nháp đơn hàng này không?" to "You have items in your import order. Do you want to save this order as a draft?",
        "Lưu nháp" to "Save Draft",
        "Thoát" to "Exit",
        "NHÁP" to "DRAFT",
        "HOÀN THÀNH" to "COMPLETE",
        "Đã lưu nháp đơn nhập hàng!" to "Import order saved as draft!",
        "Đã xác nhận hoàn thành đơn nhập hàng!" to "Confirmed completion of import order!",
        "Căn chỉnh ảnh sản phẩm" to "Adjust product image",
        "Di chuyển hoặc phóng to/thu nhỏ ảnh để vừa khung hình 1:1" to "Move or zoom the image to fit the 1:1 square frame",
        "Lỗi lưu ảnh đã cắt" to "Error saving cropped image",
        "Lỗi cắt ảnh" to "Error cropping image",
        "Không thể tải hình ảnh" to "Unable to load image",
        "Thu phóng" to "Zoom",
        "Xoay 90°" to "Rotate 90°",
        "Hoàn hàng" to "Return goods",
        "Hàng tồn:" to "Stock:",
        "Tính toán tiền hoàn lại:" to "Calculate Refund:",
        "Xác nhận hoàn hàng" to "Confirm Return",
        "Bạn có chắc chắn muốn hoàn" to "Are you sure you want to return",
        "sản phẩm với tổng số tiền là" to "items with the total amount of",
        "không?\n\nHệ thống sẽ tự động trừ kho và cộng lại tiền mặt." to "?\n\nThe system will automatically deduct stock and refund cash.",
        "Số lượng hoàn" to "Return Quantity"
    )

    fun translate(text: String, lang: String): String {
        val mappedExact = when {
            lang.contains("Anh", ignoreCase = true) || lang.contains("English", ignoreCase = true) || lang.contains("Mỹ", ignoreCase = true) || lang.contains("Mĩ", ignoreCase = true) || lang.contains("US", ignoreCase = true) -> {
                americanMap[text] ?: englishMap[text]
            }
            lang.contains("Trung", ignoreCase = true) -> {
                chineseMap[text]
            }
            else -> null
        }
        if (mappedExact != null) return mappedExact

        val trimmed = text.trim()
        val mapped = when {
            lang.contains("Anh", ignoreCase = true) || lang.contains("English", ignoreCase = true) || lang.contains("Mỹ", ignoreCase = true) || lang.contains("Mĩ", ignoreCase = true) || lang.contains("US", ignoreCase = true) -> {
                americanMap[trimmed] ?: englishMap[trimmed]
            }
            lang.contains("Trung", ignoreCase = true) -> {
                chineseMap[trimmed]
            }
            else -> null
        }
        if (mapped != null) return mapped

        // Pattern matching for dynamic templates
        val isEng = lang.contains("Anh", ignoreCase = true) || lang.contains("English", ignoreCase = true) || lang.contains("Mỹ", ignoreCase = true) || lang.contains("Mĩ", ignoreCase = true) || lang.contains("US", ignoreCase = true)
        val isChi = lang.contains("Trung", ignoreCase = true)

        if (isEng) {
            if (trimmed.startsWith("Có ") && trimmed.endsWith(" mặt hàng liên quan")) {
                val num = trimmed.substring(3, trimmed.length - 19)
                return "There are $num related products"
            }
            if (trimmed.startsWith("Có ") && trimmed.endsWith(" đơn hàng nợ")) {
                val num = trimmed.substring(3, trimmed.length - 12)
                return "There are $num credit orders"
            }
            if (trimmed.startsWith("Đã thêm ")) {
                val item = trimmed.substring(8)
                return "Added $item"
            }
            if (trimmed.startsWith("Lịch hẹn thanh toán cho hóa đơn #")) {
                val invId = trimmed.substring(33)
                return "Payment schedule for invoice #$invId"
            }
            if (trimmed.startsWith("Không thể bán quá số lượng hàng tồn! Tối đa: ")) {
                val max = trimmed.substring(45)
                return "Cannot sell more than stock quantity! Max: $max"
            }
            if (trimmed.startsWith("Không thể thêm! Vượt quá số lượng hàng tồn: ")) {
                val max = trimmed.substring(44)
                return "Cannot add! Exceeds stock quantity: $max"
            }
            if (trimmed.startsWith("... và ") && trimmed.endsWith(" sản phẩm khác. Vui lòng nhập thêm chữ để tìm chính xác hơn.")) {
                val num = trimmed.substring(7, trimmed.length - 60)
                return "... and $num other products. Please enter more characters to search precisely."
            }
            if (trimmed.contains(" (cũ) -> ") && trimmed.endsWith(" (mới)")) {
                val parts = trimmed.split(" (cũ) -> ")
                if (parts.size == 2) {
                    val oldP = parts[0]
                    val newP = parts[1].substring(0, parts[1].length - 6)
                    return "$oldP (old) -> $newP (new)"
                }
            }
            if (trimmed.startsWith("Bạn có chắc chắn muốn xóa toàn bộ công nợ của khách hàng ") && trimmed.endsWith("? Toàn bộ các hóa đơn nợ của khách hàng này sẽ được xóa.")) {
                val custName = trimmed.substring(57, trimmed.length - 56)
                return "Are you sure you want to clear all debts of customer $custName? All credit invoices of this customer will be deleted."
            }
            if (trimmed.startsWith("Bạn có chắc chắn muốn xóa sản phẩm '") && trimmed.endsWith("' khỏi danh mục này không?")) {
                val prodName = trimmed.substring(36, trimmed.length - 27)
                return "Are you sure you want to remove product '$prodName' from this category?"
            }
        } else if (isChi) {
            if (trimmed.startsWith("Có ") && trimmed.endsWith(" mặt hàng liên quan")) {
                val num = trimmed.substring(3, trimmed.length - 19)
                return "有 $num 个关联商品"
            }
            if (trimmed.startsWith("Có ") && trimmed.endsWith(" đơn hàng nợ")) {
                val num = trimmed.substring(3, trimmed.length - 12)
                return "有 $num 个欠款订单"
            }
            if (trimmed.startsWith("Đã thêm ")) {
                val item = trimmed.substring(8)
                return "已添加 $item"
            }
            if (trimmed.startsWith("Lịch hẹn thanh toán cho hóa đơn #")) {
                val invId = trimmed.substring(33)
                return "账单 #$invId 的还款安排日程"
            }
            if (trimmed.startsWith("Không thể bán quá số lượng hàng tồn! Tối đa: ")) {
                val max = trimmed.substring(45)
                return "销售数量不能超过库存量！最大: $max"
            }
            if (trimmed.startsWith("Không thể thêm! Vượt quá số lượng hàng tồn: ")) {
                val max = trimmed.substring(44)
                return "无法添加！超过库存数量: $max"
            }
            if (trimmed.startsWith("... và ") && trimmed.endsWith(" sản phẩm khác. Vui lòng nhập thêm chữ để tìm chính xác hơn.")) {
                val num = trimmed.substring(7, trimmed.length - 60)
                return "... 还有 $num 个其他产品。请输入更多字符以精确搜索。"
            }
            if (trimmed.contains(" (cũ) -> ") && trimmed.endsWith(" (mới)")) {
                val parts = trimmed.split(" (cũ) -> ")
                if (parts.size == 2) {
                    val oldP = parts[0]
                    val newP = parts[1].substring(0, parts[1].length - 6)
                    return "$oldP (旧) -> $newP (新)"
                }
            }
            if (trimmed.startsWith("Bạn có chắc chắn muốn xóa toàn bộ công nợ của khách hàng ") && trimmed.endsWith("? Toàn bộ các hóa đơn nợ của khách hàng này sẽ được xóa.")) {
                val custName = trimmed.substring(57, trimmed.length - 56)
                return "您确定要清除客户 $custName 的所有债务吗？此客户的所有欠款账单都将被删除。"
            }
            if (trimmed.startsWith("Bạn có chắc chắn muốn xóa sản phẩm '") && trimmed.endsWith("' khỏi danh mục này không?")) {
                val prodName = trimmed.substring(36, trimmed.length - 27)
                return "您确定要将产品 '$prodName' 从此分类中移除吗？"
            }
        }

        return text
    }
}

fun String.t(): String {
    return Translator.translate(this, Translator.currentLanguageState.value)
}
